//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.27 at 09:25:18 AM CEST 
//


package eu.europa.esig.dss.jaxb.detailedreport;

import javax.xml.bind.annotation.adapters.XmlAdapter;
import eu.europa.esig.dss.validation.policy.Context;

public class Adapter5
    extends XmlAdapter<String, Context>
{


    public Context unmarshal(String value) {
        return (eu.europa.esig.dss.jaxb.parsers.ContextParser.parse(value));
    }

    public String marshal(Context value) {
        return (eu.europa.esig.dss.jaxb.parsers.ContextParser.print(value));
    }

}
