//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.16 at 10:20:34 AM CET 
//


package eu.europa.esig.dss.jaxb.detailedreport;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BasicSignaturesValidation" type="{http://dss.esig.europa.eu/validation/diagnostic}BasicSignaturesValidation"/>
 *         &lt;element name="TimestampsValidation" type="{http://dss.esig.europa.eu/validation/diagnostic}TimestampsValidation"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "basicSignaturesValidation",
    "timestampsValidation"
})
@XmlRootElement(name = "ValidationData")
public class ValidationData {

    @XmlElement(name = "BasicSignaturesValidation", required = true)
    protected XmlBasicSignaturesValidation basicSignaturesValidation;
    @XmlElement(name = "TimestampsValidation", required = true)
    protected XmlTimestampsValidation timestampsValidation;

    /**
     * Gets the value of the basicSignaturesValidation property.
     * 
     * @return
     *     possible object is
     *     {@link XmlBasicSignaturesValidation }
     *     
     */
    public XmlBasicSignaturesValidation getBasicSignaturesValidation() {
        return basicSignaturesValidation;
    }

    /**
     * Sets the value of the basicSignaturesValidation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlBasicSignaturesValidation }
     *     
     */
    public void setBasicSignaturesValidation(XmlBasicSignaturesValidation value) {
        this.basicSignaturesValidation = value;
    }

    /**
     * Gets the value of the timestampsValidation property.
     * 
     * @return
     *     possible object is
     *     {@link XmlTimestampsValidation }
     *     
     */
    public XmlTimestampsValidation getTimestampsValidation() {
        return timestampsValidation;
    }

    /**
     * Sets the value of the timestampsValidation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlTimestampsValidation }
     *     
     */
    public void setTimestampsValidation(XmlTimestampsValidation value) {
        this.timestampsValidation = value;
    }

}
