//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.23 at 04:02:25 PM CET 
//


package eu.europa.esig.dss.jaxb.detailedreport;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QMatrixBlock complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QMatrixBlock">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TLAnalysis" type="{http://dss.esig.europa.eu/validation/detailed-report}TLAnalysis" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SignatureAnalysis" type="{http://dss.esig.europa.eu/validation/detailed-report}SignatureAnalysis" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QMatrixBlock", propOrder = {
    "tlAnalysis",
    "signatureAnalysis"
})
public class XmlQMatrixBlock {

    @XmlElement(name = "TLAnalysis")
    protected List<XmlTLAnalysis> tlAnalysis;
    @XmlElement(name = "SignatureAnalysis")
    protected List<XmlSignatureAnalysis> signatureAnalysis;

    /**
     * Gets the value of the tlAnalysis property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tlAnalysis property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTLAnalysis().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlTLAnalysis }
     * 
     * 
     */
    public List<XmlTLAnalysis> getTLAnalysis() {
        if (tlAnalysis == null) {
            tlAnalysis = new ArrayList<XmlTLAnalysis>();
        }
        return this.tlAnalysis;
    }

    /**
     * Gets the value of the signatureAnalysis property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the signatureAnalysis property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSignatureAnalysis().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlSignatureAnalysis }
     * 
     * 
     */
    public List<XmlSignatureAnalysis> getSignatureAnalysis() {
        if (signatureAnalysis == null) {
            signatureAnalysis = new ArrayList<XmlSignatureAnalysis>();
        }
        return this.signatureAnalysis;
    }

}
