/**
 * DSS - Digital Signature Services
 * Copyright (C) 2015 European Commission, provided under the CEF programme
 * 
 * This file is part of the "DSS - Digital Signature Services" project.
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */
package eu.europa.esig.dss.pades.signature;

import eu.europa.esig.dss.cades.CMSUtils;
import eu.europa.esig.dss.cades.signature.CMSSignedDocument;
import eu.europa.esig.dss.cades.signature.CustomContentSigner;
import eu.europa.esig.dss.enumerations.SignatureAlgorithm;
import eu.europa.esig.dss.enumerations.SignatureLevel;
import eu.europa.esig.dss.model.DSSDocument;
import eu.europa.esig.dss.model.InMemoryDocument;
import eu.europa.esig.dss.model.SignatureValue;
import eu.europa.esig.dss.model.ToBeSigned;
import eu.europa.esig.dss.pades.PAdESSignatureParameters;
import eu.europa.esig.dss.pades.PAdESTimestampParameters;
import eu.europa.esig.dss.pades.signature.suite.AbstractPAdESTestSignature;
import eu.europa.esig.dss.pdf.DSSMessageDigest;
import eu.europa.esig.dss.signature.DocumentSignatureService;
import eu.europa.esig.dss.spi.DSSASN1Utils;
import eu.europa.esig.dss.spi.DSSUtils;
import org.bouncycastle.cms.CMSProcessableByteArray;
import org.bouncycastle.cms.CMSSignedData;
import org.bouncycastle.cms.CMSSignedDataGenerator;
import org.bouncycastle.cms.SignerInfoGeneratorBuilder;
import org.junit.jupiter.api.BeforeEach;

import java.util.Date;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

public abstract class AbstractPAdESWithExternalCMSServiceTest extends AbstractPAdESTestSignature {

	private PAdESSignatureParameters signatureParameters;
	private Date signingTime;
	private DSSDocument documentToSign;

	@BeforeEach
	public void init() throws Exception {
		signingTime = new Date();
		documentToSign = new InMemoryDocument(getClass().getResourceAsStream("/sample.pdf"));
	}

	@Override
	protected DSSDocument sign() {
		PAdESWithExternalCMSService service = new PAdESWithExternalCMSService();

		PAdESSignatureParameters signatureParameters = new PAdESSignatureParameters();
		signatureParameters.bLevel().setSigningDate(signingTime);
		signatureParameters.setSignatureLevel(SignatureLevel.PAdES_BASELINE_B);
		signatureParameters.setReason("DSS testing");

		DSSMessageDigest messageDigest = service.getMessageDigest(documentToSign, signatureParameters);
		assertNotNull(messageDigest);

		// Embedded CAdES is generated by a third party
		byte[] encoded = getSignedCMSignedData(messageDigest);
		assertNotNull(encoded);
		CMSSignedData cmsSignedData = DSSUtils.toCMSSignedData(encoded);
		CMSSignedDocument cmsSignedDocument = new CMSSignedDocument(cmsSignedData);

		assertTrue(service.isValidCMSSignedData(messageDigest, cmsSignedDocument));
		assertTrue(service.isValidPAdESBaselineCMSSignedData(messageDigest, cmsSignedDocument));

		// Stateless
		service = new PAdESWithExternalCMSService();
		return service.signDocument(documentToSign, signatureParameters, cmsSignedDocument);
	}

	/**
	 * Computes a CAdES with specific things for PAdES
	 */
	private byte[] getSignedCMSignedData(DSSMessageDigest messageDigest) {
		signatureParameters = new PAdESSignatureParameters();
		signatureParameters.bLevel().setSigningDate(signingTime);
		signatureParameters.setSigningCertificate(getSigningCert());
		signatureParameters.setCertificateChain(getCertificateChain());
		signatureParameters.setSignatureLevel(SignatureLevel.PAdES_BASELINE_B);
		signatureParameters.setReason("DSS testing");

		CMSProcessableByteArray content = new CMSProcessableByteArray(messageDigest.getValue());

		PadesCMSSignedDataBuilder padesCMSSignedDataBuilder = new PadesCMSSignedDataBuilder(getOfflineCertificateVerifier());
		SignatureAlgorithm signatureAlgorithm = signatureParameters.getSignatureAlgorithm();

		CustomContentSigner customContentSigner = new CustomContentSigner(signatureAlgorithm.getJCEId());
		SignerInfoGeneratorBuilder signerInfoGeneratorBuilder = padesCMSSignedDataBuilder.getSignerInfoGeneratorBuilder(signatureParameters, messageDigest);

		CMSSignedDataGenerator generator = padesCMSSignedDataBuilder.createCMSSignedDataGenerator(signatureParameters, customContentSigner,
				signerInfoGeneratorBuilder, null);

		CMSUtils.generateDetachedCMSSignedData(generator, content);

		SignatureValue signatureValue = getToken().sign(new ToBeSigned(customContentSigner.getOutputStream().toByteArray()),
				signatureParameters.getDigestAlgorithm(), getPrivateKeyEntry());

		customContentSigner = new CustomContentSigner(signatureAlgorithm.getJCEId(), signatureValue.getValue());
		generator = padesCMSSignedDataBuilder.createCMSSignedDataGenerator(signatureParameters, customContentSigner, signerInfoGeneratorBuilder, null);

		CMSSignedData cmsSignedData = CMSUtils.generateDetachedCMSSignedData(generator, content);
		return DSSASN1Utils.getDEREncoded(cmsSignedData);
	}

	@Override
	protected DocumentSignatureService<PAdESSignatureParameters, PAdESTimestampParameters> getService() {
		return null;
	}

	@Override
	protected PAdESSignatureParameters getSignatureParameters() {
		return signatureParameters;
	}

	@Override
	protected DSSDocument getDocumentToSign() {
		return documentToSign;
	}

	@Override
	protected String getSigningAlias() {
		return GOOD_USER;
	}

}
