//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.27 at 08:54:03 AM CET 
//


package eu.europa.esig.dss.jaxb.diagnostic;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DocumentName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ValidationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="ContainerInfo" type="{http://dss.esig.europa.eu/validation/diagnostic}ContainerInfo" minOccurs="0"/&gt;
 *         &lt;element name="Signatures" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Signature" type="{http://dss.esig.europa.eu/validation/diagnostic}Signature" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="UsedCertificates" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Certificate" type="{http://dss.esig.europa.eu/validation/diagnostic}Certificate" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="UsedRevocations" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Revocation" type="{http://dss.esig.europa.eu/validation/diagnostic}Revocation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="UsedTimestamps" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Timestamp" type="{http://dss.esig.europa.eu/validation/diagnostic}Timestamp" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="TrustedLists" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="TrustedList" type="{http://dss.esig.europa.eu/validation/diagnostic}TrustedList" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ListOfTrustedLists" type="{http://dss.esig.europa.eu/validation/diagnostic}TrustedList" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "documentName",
    "validationDate",
    "containerInfo",
    "signatures",
    "usedCertificates",
    "usedRevocations",
    "usedTimestamps",
    "trustedLists",
    "listOfTrustedLists"
})
@XmlRootElement(name = "DiagnosticData")
public class DiagnosticData implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "DocumentName")
    protected String documentName;
    @XmlElement(name = "ValidationDate", required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected Date validationDate;
    @XmlElement(name = "ContainerInfo")
    protected XmlContainerInfo containerInfo;
    @XmlElementWrapper(name = "Signatures")
    @XmlElement(name = "Signature", namespace = "http://dss.esig.europa.eu/validation/diagnostic")
    protected List<XmlSignature> signatures;
    @XmlElementWrapper(name = "UsedCertificates")
    @XmlElement(name = "Certificate", namespace = "http://dss.esig.europa.eu/validation/diagnostic")
    protected List<XmlCertificate> usedCertificates;
    @XmlElementWrapper(name = "UsedRevocations")
    @XmlElement(name = "Revocation", namespace = "http://dss.esig.europa.eu/validation/diagnostic")
    protected List<XmlRevocation> usedRevocations;
    @XmlElementWrapper(name = "UsedTimestamps")
    @XmlElement(name = "Timestamp", namespace = "http://dss.esig.europa.eu/validation/diagnostic")
    protected List<XmlTimestamp> usedTimestamps;
    @XmlElementWrapper(name = "TrustedLists")
    @XmlElement(name = "TrustedList", namespace = "http://dss.esig.europa.eu/validation/diagnostic")
    protected List<XmlTrustedList> trustedLists;
    @XmlElement(name = "ListOfTrustedLists")
    protected XmlTrustedList listOfTrustedLists;

    /**
     * Gets the value of the documentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentName() {
        return documentName;
    }

    /**
     * Sets the value of the documentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentName(String value) {
        this.documentName = value;
    }

    /**
     * Gets the value of the validationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getValidationDate() {
        return validationDate;
    }

    /**
     * Sets the value of the validationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidationDate(Date value) {
        this.validationDate = value;
    }

    /**
     * Gets the value of the containerInfo property.
     * 
     * @return
     *     possible object is
     *     {@link XmlContainerInfo }
     *     
     */
    public XmlContainerInfo getContainerInfo() {
        return containerInfo;
    }

    /**
     * Sets the value of the containerInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlContainerInfo }
     *     
     */
    public void setContainerInfo(XmlContainerInfo value) {
        this.containerInfo = value;
    }

    /**
     * Gets the value of the listOfTrustedLists property.
     * 
     * @return
     *     possible object is
     *     {@link XmlTrustedList }
     *     
     */
    public XmlTrustedList getListOfTrustedLists() {
        return listOfTrustedLists;
    }

    /**
     * Sets the value of the listOfTrustedLists property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlTrustedList }
     *     
     */
    public void setListOfTrustedLists(XmlTrustedList value) {
        this.listOfTrustedLists = value;
    }

    public List<XmlSignature> getSignatures() {
        if (signatures == null) {
            signatures = new ArrayList<XmlSignature>();
        }
        return signatures;
    }

    public void setSignatures(List<XmlSignature> signatures) {
        this.signatures = signatures;
    }

    public List<XmlCertificate> getUsedCertificates() {
        if (usedCertificates == null) {
            usedCertificates = new ArrayList<XmlCertificate>();
        }
        return usedCertificates;
    }

    public void setUsedCertificates(List<XmlCertificate> usedCertificates) {
        this.usedCertificates = usedCertificates;
    }

    public List<XmlRevocation> getUsedRevocations() {
        if (usedRevocations == null) {
            usedRevocations = new ArrayList<XmlRevocation>();
        }
        return usedRevocations;
    }

    public void setUsedRevocations(List<XmlRevocation> usedRevocations) {
        this.usedRevocations = usedRevocations;
    }

    public List<XmlTimestamp> getUsedTimestamps() {
        if (usedTimestamps == null) {
            usedTimestamps = new ArrayList<XmlTimestamp>();
        }
        return usedTimestamps;
    }

    public void setUsedTimestamps(List<XmlTimestamp> usedTimestamps) {
        this.usedTimestamps = usedTimestamps;
    }

    public List<XmlTrustedList> getTrustedLists() {
        if (trustedLists == null) {
            trustedLists = new ArrayList<XmlTrustedList>();
        }
        return trustedLists;
    }

    public void setTrustedLists(List<XmlTrustedList> trustedLists) {
        this.trustedLists = trustedLists;
    }

}
