//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.26 at 09:19:39 AM CET 
//


package eu.europa.esig.dss.jaxb.diagnostic;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.europa.esig.dss.jaxb.diagnostic package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.europa.esig.dss.jaxb.diagnostic
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DiagnosticData }
     * 
     */
    public DiagnosticData createDiagnosticData() {
        return new DiagnosticData();
    }

    /**
     * Create an instance of {@link XmlContainerInfo }
     * 
     */
    public XmlContainerInfo createXmlContainerInfo() {
        return new XmlContainerInfo();
    }

    /**
     * Create an instance of {@link XmlTrustedList }
     * 
     */
    public XmlTrustedList createXmlTrustedList() {
        return new XmlTrustedList();
    }

    /**
     * Create an instance of {@link XmlPolicy }
     * 
     */
    public XmlPolicy createXmlPolicy() {
        return new XmlPolicy();
    }

    /**
     * Create an instance of {@link XmlStructuralValidation }
     * 
     */
    public XmlStructuralValidation createXmlStructuralValidation() {
        return new XmlStructuralValidation();
    }

    /**
     * Create an instance of {@link XmlCertifiedRole }
     * 
     */
    public XmlCertifiedRole createXmlCertifiedRole() {
        return new XmlCertifiedRole();
    }

    /**
     * Create an instance of {@link XmlDistinguishedName }
     * 
     */
    public XmlDistinguishedName createXmlDistinguishedName() {
        return new XmlDistinguishedName();
    }

    /**
     * Create an instance of {@link XmlSigningCertificate }
     * 
     */
    public XmlSigningCertificate createXmlSigningCertificate() {
        return new XmlSigningCertificate();
    }

    /**
     * Create an instance of {@link XmlTrustedServiceProvider }
     * 
     */
    public XmlTrustedServiceProvider createXmlTrustedServiceProvider() {
        return new XmlTrustedServiceProvider();
    }

    /**
     * Create an instance of {@link XmlOID }
     * 
     */
    public XmlOID createXmlOID() {
        return new XmlOID();
    }

    /**
     * Create an instance of {@link XmlSignatureProductionPlace }
     * 
     */
    public XmlSignatureProductionPlace createXmlSignatureProductionPlace() {
        return new XmlSignatureProductionPlace();
    }

    /**
     * Create an instance of {@link XmlTimestamp }
     * 
     */
    public XmlTimestamp createXmlTimestamp() {
        return new XmlTimestamp();
    }

    /**
     * Create an instance of {@link XmlManifestFile }
     * 
     */
    public XmlManifestFile createXmlManifestFile() {
        return new XmlManifestFile();
    }

    /**
     * Create an instance of {@link XmlBasicSignature }
     * 
     */
    public XmlBasicSignature createXmlBasicSignature() {
        return new XmlBasicSignature();
    }

    /**
     * Create an instance of {@link XmlSignedObjects }
     * 
     */
    public XmlSignedObjects createXmlSignedObjects() {
        return new XmlSignedObjects();
    }

    /**
     * Create an instance of {@link XmlDigestAlgoAndValue }
     * 
     */
    public XmlDigestAlgoAndValue createXmlDigestAlgoAndValue() {
        return new XmlDigestAlgoAndValue();
    }

    /**
     * Create an instance of {@link XmlSignature }
     * 
     */
    public XmlSignature createXmlSignature() {
        return new XmlSignature();
    }

    /**
     * Create an instance of {@link XmlSignatureScope }
     * 
     */
    public XmlSignatureScope createXmlSignatureScope() {
        return new XmlSignatureScope();
    }

    /**
     * Create an instance of {@link XmlTrustedService }
     * 
     */
    public XmlTrustedService createXmlTrustedService() {
        return new XmlTrustedService();
    }

    /**
     * Create an instance of {@link XmlCertificate }
     * 
     */
    public XmlCertificate createXmlCertificate() {
        return new XmlCertificate();
    }

    /**
     * Create an instance of {@link XmlRevocation }
     * 
     */
    public XmlRevocation createXmlRevocation() {
        return new XmlRevocation();
    }

    /**
     * Create an instance of {@link XmlMessage }
     * 
     */
    public XmlMessage createXmlMessage() {
        return new XmlMessage();
    }

    /**
     * Create an instance of {@link XmlChainItem }
     * 
     */
    public XmlChainItem createXmlChainItem() {
        return new XmlChainItem();
    }

    /**
     * Create an instance of {@link XmlSignedSignature }
     * 
     */
    public XmlSignedSignature createXmlSignedSignature() {
        return new XmlSignedSignature();
    }

    /**
     * Create an instance of {@link XmlTimestampedTimestamp }
     * 
     */
    public XmlTimestampedTimestamp createXmlTimestampedTimestamp() {
        return new XmlTimestampedTimestamp();
    }

}
