//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.31 at 09:13:27 AM CEST 
//


package eu.europa.esig.dss.jaxb.diagnostic;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RelatedCertificate" type="{http://dss.esig.europa.eu/validation/diagnostic}RelatedCertificate" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="OrphanCertificate" type="{http://dss.esig.europa.eu/validation/diagnostic}OrphanCertificate" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "relatedCertificates",
    "orphanCertificates"
})
public class XmlFoundCertificates implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "RelatedCertificate")
    protected List<XmlRelatedCertificate> relatedCertificates;
    @XmlElement(name = "OrphanCertificate")
    protected List<XmlOrphanCertificate> orphanCertificates;

    /**
     * Gets the value of the relatedCertificates property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedCertificates property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedCertificates().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlRelatedCertificate }
     * 
     * 
     */
    public List<XmlRelatedCertificate> getRelatedCertificates() {
        if (relatedCertificates == null) {
            relatedCertificates = new ArrayList<XmlRelatedCertificate>();
        }
        return this.relatedCertificates;
    }

    /**
     * Gets the value of the orphanCertificates property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orphanCertificates property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrphanCertificates().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlOrphanCertificate }
     * 
     * 
     */
    public List<XmlOrphanCertificate> getOrphanCertificates() {
        if (orphanCertificates == null) {
            orphanCertificates = new ArrayList<XmlOrphanCertificate>();
        }
        return this.orphanCertificates;
    }

}
