//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.29 at 10:40:07 AM CET 
//


package eu.europa.esig.dss.jaxb.diagnostic;

import java.io.Serializable;
import java.util.Date;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import eu.europa.esig.dss.validation.RevocationRefLocation;
import eu.europa.esig.dss.validation.RevocationType;


/**
 * <p>Java class for RevocationRef complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RevocationRef"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DigestAlgoAndValue" type="{http://dss.esig.europa.eu/validation/diagnostic}DigestAlgoAndValue" minOccurs="0"/&gt;
 *         &lt;element name="ProducedAt" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;choice minOccurs="0"&gt;
 *           &lt;element name="ResponderIdName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *           &lt;element name="ResponderIdKey" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Type" type="{http://dss.esig.europa.eu/validation/diagnostic}RevocationType" /&gt;
 *       &lt;attribute name="Location" use="required" type="{http://dss.esig.europa.eu/validation/diagnostic}RevocationRefLocationType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RevocationRef", propOrder = {
    "digestAlgoAndValue",
    "producedAt",
    "responderIdName",
    "responderIdKey"
})
public class XmlRevocationRef implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "DigestAlgoAndValue")
    protected XmlDigestAlgoAndValue digestAlgoAndValue;
    @XmlElement(name = "ProducedAt", type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected Date producedAt;
    @XmlElement(name = "ResponderIdName")
    protected String responderIdName;
    @XmlElement(name = "ResponderIdKey")
    protected byte[] responderIdKey;
    @XmlAttribute(name = "Type")
    @XmlJavaTypeAdapter(Adapter5 .class)
    protected RevocationType type;
    @XmlAttribute(name = "Location", required = true)
    @XmlJavaTypeAdapter(Adapter7 .class)
    protected RevocationRefLocation location;

    /**
     * Gets the value of the digestAlgoAndValue property.
     * 
     * @return
     *     possible object is
     *     {@link XmlDigestAlgoAndValue }
     *     
     */
    public XmlDigestAlgoAndValue getDigestAlgoAndValue() {
        return digestAlgoAndValue;
    }

    /**
     * Sets the value of the digestAlgoAndValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlDigestAlgoAndValue }
     *     
     */
    public void setDigestAlgoAndValue(XmlDigestAlgoAndValue value) {
        this.digestAlgoAndValue = value;
    }

    /**
     * Gets the value of the producedAt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getProducedAt() {
        return producedAt;
    }

    /**
     * Sets the value of the producedAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProducedAt(Date value) {
        this.producedAt = value;
    }

    /**
     * Gets the value of the responderIdName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponderIdName() {
        return responderIdName;
    }

    /**
     * Sets the value of the responderIdName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponderIdName(String value) {
        this.responderIdName = value;
    }

    /**
     * Gets the value of the responderIdKey property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getResponderIdKey() {
        return responderIdKey;
    }

    /**
     * Sets the value of the responderIdKey property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setResponderIdKey(byte[] value) {
        this.responderIdKey = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public RevocationType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(RevocationType value) {
        this.type = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public RevocationRefLocation getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation(RevocationRefLocation value) {
        this.location = value;
    }

}
