<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>eu.europa.ec.joinup.sd-dss</groupId>
        <artifactId>sd-dss</artifactId>
        <version>6.6-SNAPSHOT</version>
    </parent>

    <artifactId>dss-attestation-validation-rest</artifactId>
    <name>DSS EAA Validation REST</name>
    <description>REST server for performing of a validation of Electronic Attestation of Attributes (EAA) or EAA Presentations using the WebServices</description>

    <properties>
        <module-name>jpms_dss_ws_eaa_validation_remote_rest</module-name>
    </properties>

    <dependencies>
        <dependency>
            <groupId>eu.europa.ec.joinup.sd-dss</groupId>
            <artifactId>dss-attestation-validation-remote</artifactId>
        </dependency>
        <dependency>
            <groupId>eu.europa.ec.joinup.sd-dss</groupId>
            <artifactId>dss-attestation-validation-rest-client</artifactId>
        </dependency>
    </dependencies>
</project>