<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>eu.europa.ec.joinup.sd-dss</groupId>
        <artifactId>sd-dss</artifactId>
        <version>6.6-SNAPSHOT</version>
    </parent>

    <artifactId>dss-attestation-creation-rest-client</artifactId>
    <name>DSS EAA Creation REST client</name>
    <description>REST client for performing of a signature of Electronic Attestation of Attributes (EAA) and issuance of EAA Presentations using the WebServices</description>

    <properties>
        <module-name>jpms_dss_ws_eaa_creation_remote_rest_client</module-name>
    </properties>

    <dependencies>
        <dependency>
            <groupId>eu.europa.ec.joinup.sd-dss</groupId>
            <artifactId>dss-attestation-creation-dto</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.ws.rs</groupId>
            <artifactId>jakarta.ws.rs-api</artifactId>
        </dependency>
    </dependencies>
</project>