package eu.europa.esig.dss.validation;

public enum XmlTimestampType {
	
	CONTENT_TIMESTAMP, 
	ALL_DATA_OBJECTS_TIMESTAMP,
	INDIVIDUAL_DATA_OBJECTS_TIMESTAMP,
	SIGNATURE_TIMESTAMP,
	VALIDATION_DATA_REFSONLY_TIMESTAMP,
	VALIDATION_DATA_TIMESTAMP,
	ARCHIVE_TIMESTAMP,

}
