//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.29 at 02:49:27 PM CEST 
//


package eu.europa.esig.jaxb.policy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="MainSignature"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="StructuralValidation" type="{http://dss.esig.europa.eu/validation/diagnostic}LevelConstraint" minOccurs="0"/&gt;
 *                   &lt;element name="AcceptablePolicies" type="{http://dss.esig.europa.eu/validation/diagnostic}MultiValuesConstraint" minOccurs="0"/&gt;
 *                   &lt;element name="ReferenceDataExistence" type="{http://dss.esig.europa.eu/validation/diagnostic}LevelConstraint" minOccurs="0"/&gt;
 *                   &lt;element name="ReferenceDataIntact" type="{http://dss.esig.europa.eu/validation/diagnostic}LevelConstraint" minOccurs="0"/&gt;
 *                   &lt;element name="SignatureIntact" type="{http://dss.esig.europa.eu/validation/diagnostic}LevelConstraint" minOccurs="0"/&gt;
 *                   &lt;element name="SigningCertificate" type="{http://dss.esig.europa.eu/validation/diagnostic}CertificateType"/&gt;
 *                   &lt;element name="CACertificate" type="{http://dss.esig.europa.eu/validation/diagnostic}CertificateType"/&gt;
 *                   &lt;element name="Cryptographic" type="{http://dss.esig.europa.eu/validation/diagnostic}CryptographicType"/&gt;
 *                   &lt;element name="MandatedSignedQProperties" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="SigningTime" type="{http://dss.esig.europa.eu/validation/diagnostic}LevelConstraint"/&gt;
 *                             &lt;element name="ContentTimeStamp" type="{http://dss.esig.europa.eu/validation/diagnostic}ContentTimeStampType"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="MandatedUnsignedQProperties" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="CounterSignature" type="{http://dss.esig.europa.eu/validation/diagnostic}CounterSignatureType"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Timestamp"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="TimestampDelay" type="{http://dss.esig.europa.eu/validation/diagnostic}TimeConstraint"/&gt;
 *                   &lt;element name="MessageImprintDataFound" type="{http://dss.esig.europa.eu/validation/diagnostic}LevelConstraint"/&gt;
 *                   &lt;element name="MessageImprintDataIntact" type="{http://dss.esig.europa.eu/validation/diagnostic}LevelConstraint"/&gt;
 *                   &lt;element name="RevocationTimeAgainstBestSignatureTime" type="{http://dss.esig.europa.eu/validation/diagnostic}LevelConstraint"/&gt;
 *                   &lt;element name="BestSignatureTimeBeforeIssuanceDateOfSigningCertificate" type="{http://dss.esig.europa.eu/validation/diagnostic}LevelConstraint"/&gt;
 *                   &lt;element name="SigningCertificateValidityAtBestSignatureTime" type="{http://dss.esig.europa.eu/validation/diagnostic}LevelConstraint"/&gt;
 *                   &lt;element name="AlgorithmReliableAtBestSignatureTime" type="{http://dss.esig.europa.eu/validation/diagnostic}LevelConstraint"/&gt;
 *                   &lt;element name="Coherence" type="{http://dss.esig.europa.eu/validation/diagnostic}LevelConstraint"/&gt;
 *                   &lt;element name="RightOrder" type="{http://dss.esig.europa.eu/validation/diagnostic}LevelConstraint"/&gt;
 *                   &lt;element name="SigningCertificate" type="{http://dss.esig.europa.eu/validation/diagnostic}CertificateType"/&gt;
 *                   &lt;element name="CACertificate" type="{http://dss.esig.europa.eu/validation/diagnostic}CertificateType"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Revocation"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="RevocationFreshness" type="{http://dss.esig.europa.eu/validation/diagnostic}TimeConstraint"/&gt;
 *                   &lt;element name="SigningCertificate" type="{http://dss.esig.europa.eu/validation/diagnostic}CertificateType"/&gt;
 *                   &lt;element name="CACertificate" type="{http://dss.esig.europa.eu/validation/diagnostic}CertificateType"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Cryptographic"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="AlgoExpirationDate"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Algo" type="{http://dss.esig.europa.eu/validation/diagnostic}Algo" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="Format" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "description",
    "mainSignature",
    "timestamp",
    "revocation",
    "cryptographic"
})
@XmlRootElement(name = "ConstraintsParameters")
public class ConstraintsParameters {

    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "MainSignature", required = true)
    protected MainSignature mainSignature;
    @XmlElement(name = "Timestamp", required = true)
    protected Timestamp timestamp;
    @XmlElement(name = "Revocation", required = true)
    protected Revocation revocation;
    @XmlElement(name = "Cryptographic", required = true)
    protected Cryptographic cryptographic;
    @XmlAttribute(name = "Name")
    protected String name;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the mainSignature property.
     * 
     * @return
     *     possible object is
     *     {@link MainSignature }
     *     
     */
    public MainSignature getMainSignature() {
        return mainSignature;
    }

    /**
     * Sets the value of the mainSignature property.
     * 
     * @param value
     *     allowed object is
     *     {@link MainSignature }
     *     
     */
    public void setMainSignature(MainSignature value) {
        this.mainSignature = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link Timestamp }
     *     
     */
    public Timestamp getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Timestamp }
     *     
     */
    public void setTimestamp(Timestamp value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the revocation property.
     * 
     * @return
     *     possible object is
     *     {@link Revocation }
     *     
     */
    public Revocation getRevocation() {
        return revocation;
    }

    /**
     * Sets the value of the revocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Revocation }
     *     
     */
    public void setRevocation(Revocation value) {
        this.revocation = value;
    }

    /**
     * Gets the value of the cryptographic property.
     * 
     * @return
     *     possible object is
     *     {@link Cryptographic }
     *     
     */
    public Cryptographic getCryptographic() {
        return cryptographic;
    }

    /**
     * Sets the value of the cryptographic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cryptographic }
     *     
     */
    public void setCryptographic(Cryptographic value) {
        this.cryptographic = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
