//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.29 at 04:14:22 PM CEST 
//


package eu.europa.esig.jaxb.policy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CryptographicType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CryptographicType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AcceptableEncryptionAlgo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Algo" type="{http://dss.esig.europa.eu/validation/diagnostic}Algo" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MiniPublicKeySize">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Algo" type="{http://dss.esig.europa.eu/validation/diagnostic}Algo" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AcceptableDigestAlgo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Algo" type="{http://dss.esig.europa.eu/validation/diagnostic}Algo" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="Level" type="{http://dss.esig.europa.eu/validation/diagnostic}level" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CryptographicType", propOrder = {
    "acceptableEncryptionAlgo",
    "miniPublicKeySize",
    "acceptableDigestAlgo"
})
public class CryptographicType {

    @XmlElement(name = "AcceptableEncryptionAlgo", required = true)
    protected AcceptableEncryptionAlgo acceptableEncryptionAlgo;
    @XmlElement(name = "MiniPublicKeySize", required = true)
    protected MiniPublicKeySize miniPublicKeySize;
    @XmlElement(name = "AcceptableDigestAlgo", required = true)
    protected AcceptableDigestAlgo acceptableDigestAlgo;
    @XmlAttribute(name = "Level")
    protected Level level;

    /**
     * Gets the value of the acceptableEncryptionAlgo property.
     * 
     * @return
     *     possible object is
     *     {@link AcceptableEncryptionAlgo }
     *     
     */
    public AcceptableEncryptionAlgo getAcceptableEncryptionAlgo() {
        return acceptableEncryptionAlgo;
    }

    /**
     * Sets the value of the acceptableEncryptionAlgo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcceptableEncryptionAlgo }
     *     
     */
    public void setAcceptableEncryptionAlgo(AcceptableEncryptionAlgo value) {
        this.acceptableEncryptionAlgo = value;
    }

    /**
     * Gets the value of the miniPublicKeySize property.
     * 
     * @return
     *     possible object is
     *     {@link MiniPublicKeySize }
     *     
     */
    public MiniPublicKeySize getMiniPublicKeySize() {
        return miniPublicKeySize;
    }

    /**
     * Sets the value of the miniPublicKeySize property.
     * 
     * @param value
     *     allowed object is
     *     {@link MiniPublicKeySize }
     *     
     */
    public void setMiniPublicKeySize(MiniPublicKeySize value) {
        this.miniPublicKeySize = value;
    }

    /**
     * Gets the value of the acceptableDigestAlgo property.
     * 
     * @return
     *     possible object is
     *     {@link AcceptableDigestAlgo }
     *     
     */
    public AcceptableDigestAlgo getAcceptableDigestAlgo() {
        return acceptableDigestAlgo;
    }

    /**
     * Sets the value of the acceptableDigestAlgo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcceptableDigestAlgo }
     *     
     */
    public void setAcceptableDigestAlgo(AcceptableDigestAlgo value) {
        this.acceptableDigestAlgo = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link Level }
     *     
     */
    public Level getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link Level }
     *     
     */
    public void setLevel(Level value) {
        this.level = value;
    }

}
