//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.24 at 06:43:16 AM CET 
//


package eu.europa.esig.jaxb.policy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for eIDAS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eIDAS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TLFreshness" type="{http://dss.esig.europa.eu/validation/policy}TimeConstraint" minOccurs="0"/>
 *         &lt;element name="TLNotExpired" type="{http://dss.esig.europa.eu/validation/policy}LevelConstraint" minOccurs="0"/>
 *         &lt;element name="TLWellSigned" type="{http://dss.esig.europa.eu/validation/policy}LevelConstraint" minOccurs="0"/>
 *         &lt;element name="TLVersion" type="{http://dss.esig.europa.eu/validation/policy}ValueConstraint" minOccurs="0"/>
 *         &lt;element name="TLConsistency" type="{http://dss.esig.europa.eu/validation/policy}LevelConstraint" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eIDAS", propOrder = {
    "tlFreshness",
    "tlNotExpired",
    "tlWellSigned",
    "tlVersion",
    "tlConsistency"
})
public class EIDAS {

    @XmlElement(name = "TLFreshness")
    protected TimeConstraint tlFreshness;
    @XmlElement(name = "TLNotExpired")
    protected LevelConstraint tlNotExpired;
    @XmlElement(name = "TLWellSigned")
    protected LevelConstraint tlWellSigned;
    @XmlElement(name = "TLVersion")
    protected ValueConstraint tlVersion;
    @XmlElement(name = "TLConsistency")
    protected LevelConstraint tlConsistency;

    /**
     * Gets the value of the tlFreshness property.
     * 
     * @return
     *     possible object is
     *     {@link TimeConstraint }
     *     
     */
    public TimeConstraint getTLFreshness() {
        return tlFreshness;
    }

    /**
     * Sets the value of the tlFreshness property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeConstraint }
     *     
     */
    public void setTLFreshness(TimeConstraint value) {
        this.tlFreshness = value;
    }

    /**
     * Gets the value of the tlNotExpired property.
     * 
     * @return
     *     possible object is
     *     {@link LevelConstraint }
     *     
     */
    public LevelConstraint getTLNotExpired() {
        return tlNotExpired;
    }

    /**
     * Sets the value of the tlNotExpired property.
     * 
     * @param value
     *     allowed object is
     *     {@link LevelConstraint }
     *     
     */
    public void setTLNotExpired(LevelConstraint value) {
        this.tlNotExpired = value;
    }

    /**
     * Gets the value of the tlWellSigned property.
     * 
     * @return
     *     possible object is
     *     {@link LevelConstraint }
     *     
     */
    public LevelConstraint getTLWellSigned() {
        return tlWellSigned;
    }

    /**
     * Sets the value of the tlWellSigned property.
     * 
     * @param value
     *     allowed object is
     *     {@link LevelConstraint }
     *     
     */
    public void setTLWellSigned(LevelConstraint value) {
        this.tlWellSigned = value;
    }

    /**
     * Gets the value of the tlVersion property.
     * 
     * @return
     *     possible object is
     *     {@link ValueConstraint }
     *     
     */
    public ValueConstraint getTLVersion() {
        return tlVersion;
    }

    /**
     * Sets the value of the tlVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueConstraint }
     *     
     */
    public void setTLVersion(ValueConstraint value) {
        this.tlVersion = value;
    }

    /**
     * Gets the value of the tlConsistency property.
     * 
     * @return
     *     possible object is
     *     {@link LevelConstraint }
     *     
     */
    public LevelConstraint getTLConsistency() {
        return tlConsistency;
    }

    /**
     * Sets the value of the tlConsistency property.
     * 
     * @param value
     *     allowed object is
     *     {@link LevelConstraint }
     *     
     */
    public void setTLConsistency(LevelConstraint value) {
        this.tlConsistency = value;
    }

}
