<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>eu.europa.ec.joinup.sd-dss</groupId>
        <artifactId>sd-dss</artifactId>
        <version>6.6-SNAPSHOT</version>
    </parent>

    <artifactId>dss-attestation-creation-soap</artifactId>
    <name>DSS Attestation Creation SOAP</name>
    <description>SOAP server for performing of a signature of annotations (EAA, PID, etc.) and issuance of annotation presentations using the WebServices</description>

    <properties>
        <module-name>jpms_dss_ws_attestation_creation_remote_soap</module-name>
    </properties>

    <dependencies>
        <dependency>
            <groupId>eu.europa.ec.joinup.sd-dss</groupId>
            <artifactId>dss-attestation-creation-soap-client</artifactId>
        </dependency>
        <dependency>
            <groupId>eu.europa.ec.joinup.sd-dss</groupId>
            <artifactId>dss-attestation-creation-remote</artifactId>
        </dependency>
    </dependencies>
</project>