/**
 * DSS - Digital Signature Services
 * Copyright (C) 2015 European Commission, provided under the CEF programme
 * 
 * This file is part of the "DSS - Digital Signature Services" project.
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */
package eu.europa.esig.dss.cookbook.example.sources;

import eu.europa.esig.dss.asic.common.ContainerEntryDocument;
import eu.europa.esig.dss.asic.common.DSSZipEntry;
import eu.europa.esig.dss.cades.signature.CMSSignedDocument;
import eu.europa.esig.dss.enumerations.DigestAlgorithm;
import eu.europa.esig.dss.jades.HTTPHeader;
import eu.europa.esig.dss.jades.HTTPHeaderDigest;
import eu.europa.esig.dss.model.DSSDocument;
import eu.europa.esig.dss.model.DigestDocument;
import eu.europa.esig.dss.model.FileDocument;
import eu.europa.esig.dss.model.InMemoryDocument;
import eu.europa.esig.dss.utils.Utils;
import org.bouncycastle.cms.CMSException;
import org.bouncycastle.cms.CMSSignedData;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Date;
import java.util.zip.ZipEntry;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.fail;

class DSSDocumentTest {

	@Test
	void testInMemoryDocument() throws IOException {

		// tag::inMemoryDocument[]
		// import eu.europa.esig.dss.model.DSSDocument;
		// import eu.europa.esig.dss.model.InMemoryDocument;
		// import java.io.InputStream;
		// import java.nio.file.Files;
		// import java.nio.file.Paths;

		// We can instantiate an InMemoryDocument from binaries
		DSSDocument binaryInMemoryDocument = new InMemoryDocument("Hello World".getBytes());

		// Or from InputStream
		DSSDocument isInMemoryDocument;
		try (InputStream is = Files.newInputStream(Paths.get("src/main/resources/xml_example.xml"))) {
			isInMemoryDocument = new InMemoryDocument(is);
		}
		// end::inMemoryDocument[]

		assertNotNull(binaryInMemoryDocument.getDigestValue(DigestAlgorithm.SHA256));
		assertNotNull(isInMemoryDocument.getDigestValue(DigestAlgorithm.SHA256));

		try (InputStream is = binaryInMemoryDocument.openStream()) {
			// expected behavior
		} catch (UnsupportedOperationException | IOException e) {
			fail("Cannot open an InMemoryDocument");
		}
		try (InputStream is = isInMemoryDocument.openStream()) {
			// expected behavior
		} catch (UnsupportedOperationException | IOException e) {
			fail("Cannot open an InMemoryDocument");
		}

	}

	@Test
	void testFileDocument() {

		// tag::fileDocument[]
		// import eu.europa.esig.dss.model.DSSDocument;
		// import eu.europa.esig.dss.model.FileDocument;
		// import java.io.File;

		// Instantiate a FileDocument from a File
		DSSDocument fileDocument = new FileDocument(new File("src/main/resources/xml_example.xml"));

		// Or from file path directly
		DSSDocument filePathDocument = new FileDocument("src/main/resources/xml_example.xml");

		// end::fileDocument[]

		assertNotNull(fileDocument.getDigestValue(DigestAlgorithm.SHA256));
		assertNotNull(filePathDocument.getDigestValue(DigestAlgorithm.SHA256));

		try (InputStream is = fileDocument.openStream()) {
			// expected behavior
		} catch (UnsupportedOperationException | IOException e) {
			fail("Cannot open an InMemoryDocument");
		}
		try (InputStream is = filePathDocument.openStream()) {
			// expected behavior
		} catch (UnsupportedOperationException | IOException e) {
			fail("Cannot open an InMemoryDocument");
		}

	}

	@Test
	void testDigestDocument() {

		// tag::digestDocument[]
		// import eu.europa.esig.dss.model.DSSDocument;
		// import eu.europa.esig.dss.model.DigestDocument;
		// import eu.europa.esig.dss.model.FileDocument;
		// import eu.europa.esig.dss.enumerations.DigestAlgorithm;

		// Firstly, we load a basic DSSDocument (FileDocument or InMemoryDocument)
		DSSDocument fileDocument = new FileDocument("src/main/resources/xml_example.xml");

		// After that, we create a DigestDocument
		DigestDocument digestDocument = new DigestDocument(DigestAlgorithm.SHA1, fileDocument.getDigestValue(DigestAlgorithm.SHA1));
		digestDocument.setName(fileDocument.getName());

		// We can add additional digest values when required. Eg : for a SHA-256 based signature
		digestDocument.addDigest(DigestAlgorithm.SHA256, fileDocument.getDigestValue(DigestAlgorithm.SHA256));

		// Or incorporate digest value as a String directly
		digestDocument.addDigest(DigestAlgorithm.SHA512, "T1h8Ss0fiK0pfo1chVoLumIhyIgR9I0g8IvPhJPxwnR5dPFhLDEMU5kpt3AE4xnU2dagh6JaMz1INaCkO0LItg==");

		// end::digestDocument[]

		assertNotNull(digestDocument.getDigestValue(DigestAlgorithm.SHA256));

		try {
			digestDocument.getDigestValue(DigestAlgorithm.SHA384);
			fail("SHA-384 doesn't exist");
		} catch (IllegalArgumentException e) {
			// normal behavior
		}

		try (InputStream is = digestDocument.openStream()) {
			fail("Cannot open a DigestDocument");
		} catch (UnsupportedOperationException | IOException e) {
			// normal behavior
		}

	}

	@Test
	void testCMSDocument() throws CMSException {

		byte[] cmsBytes = Utils.fromBase64("MII36QYJKoZIhvcNAQcCoII32jCCN9YCAQExCzAJBgUrDgMCGgUAMBkGCSqGSIb3DQEHAaAMBAp0b0JlU2lnbmVkoIIT6jCCBYYwggRuoAMCAQICBwJYkdUnTIgwDQYJKoZIhvcNAQELBQAwTzELMAkGA1UEBhMCRlIxDTALBgNVBAoTBEVUU0kxHDAaBgNVBAsME1BsdWd0ZXN0c18yMDEzLTIwMTQxEzARBgNVBAMTCkxldmVsQkNBT0swHhcNMTMxMjAyMDkyMzQxWhcNMTQxMjAyMDkyMzQxWjBDMQswCQYDVQQGEwJSTzEMMAoGA1UEChMDTUlEMQswCQYDVQQLEwJJVDEZMBcGA1UEAxMQTXIuIEFkcmlhbiBBbmVjaTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALeXCtH3FflxS+Hn5f+BYjqB55HkYAjkeliGFCl9RXcuExgLHvPea0VDpdE2J8n6/SjrtSd+bofyXNZlknQesx041TGSLX/Xoi+RNLd7CGxoISiGSy3/fVy8tCmoX8O0AG+s6W/R81nxNEmCNi5ujFdW4PPSSABAWfihfFT4d9KcCCGOkWNv79ARaH+SkSNZyzGrRJgXZp4pVw9vhOJ6PW1g22IYSUj8L+BByyrclfv8klg7f4oQX/bLlJttfYNu4wxjRMvNDcwxIBPgg6cfN5AIErBV8jJ4y5G9JPCBq7YJKgiGyT1F8yI7SZAaIH1hV8MCZChIkkKtFXEM/bCXOIUCAwEAAaOCAnEwggJtMA4GA1UdDwEB/wQEAwIHgDAdBgNVHQ4EFgQUyilCSkvm6RHEoXAKaCe1RETpWkowgc0GA1UdHwSBxTCBwjCBv6CBvKCBuYZvbGRhcDovL3hhZGVzc3J2LnBsdWd0ZXN0cy5uZXQvQ049TGV2ZWxCQ0FPSyxPVT1QbHVndGVzdHNfMjAxMy0yMDE0LE89RVRTSSxDPUZSP2NlcnRpZmljYXRlUmV2b2NhdGlvbkxpc3Q7YmluYXJ5hkZodHRwOi8veGFkZXNzcnYucGx1Z3Rlc3RzLm5ldC9wcm90ZWN0ZWQvY2Fwc28vY3Jscy9TQ09LL0xldmVsQkNBT0suY3JsMIIBJgYIKwYBBQUHAQEEggEYMIIBFDBTBggrBgEFBQcwAoZHaHR0cDovL3hhZGVzc3J2LnBsdWd0ZXN0cy5uZXQvcHJvdGVjdGVkL2NhcHNvL2NlcnRzL1NDT0svTGV2ZWxCQ0FPSy5jZXIwbwYIKwYBBQUHMAKGY2xkYXA6Ly94YWRlc3Nydi5wbHVndGVzdHMubmV0L0NOPUxldmVsQkNBT0ssT1U9UGx1Z3Rlc3RzXzIwMTMtMjAxNCxPPUVUU0ksQz1GUj9jQUNlcnRpZmljYXRlO2JpbmFyeTBMBggrBgEFBQcwAYZAaHR0cDovL3hhZGVzc3J2LnBsdWd0ZXN0cy5uZXQvcHJvdGVjdGVkL2NhcHNvL09DU1A/Y2E9TGV2ZWxCQ0FPSzAhBgNVHREEGjAYgRZsYXVyZW50LnZlbGV6QGV0c2kub3JnMB8GA1UdIwQYMBaAFO/pP100h1WFSEnpe8nKB8ifBKMDMA0GCSqGSIb3DQEBCwUAA4IBAQBLJxD1uuAErJXk8DuUySmzoAlHenZ3YYzse5rwB2EcuMsuBhlpD6G1UMYoBckQje/uVDt8/5lvISNik7PlX+UtDfFvl+lBiRKOGnVt0pRpNJ9MtLaj6SnWChIZ3cZcd5ToPRMtt04dN5hf1+PX1bfnJsOz3z+3OnkDjcelSBAxEEQnuta9NTo2brIhSNlw5Z86LxOR+caUPyezNPKrSmP1Up9kjJ2WOU92uoZJQnHnVUH0/1X19LI5JaWConEca4zN21LjuEA0bRkTlp2GozvfxAdq6E3VSsB8fTIZPpdAoSn0KVZ1R7NjZsamNE4kdcUq056eQwqhmvVX5EczIbumMIIFgTCCBGmgAwIBAgIIHdVKCKd/MVgwDQYJKoZIhvcNAQELBQAwTzELMAkGA1UEBhMCRlIxDTALBgNVBAoTBEVUU0kxHDAaBgNVBAsME1BsdWd0ZXN0c18yMDEzLTIwMTQxEzARBgNVBAMTCkxldmVsQUNBT0swHhcNMTMxMTEzMDExMzI0WhcNMTUxMTEzMDExMzI0WjBPMQswCQYDVQQGEwJGUjENMAsGA1UEChMERVRTSTEcMBoGA1UECwwTUGx1Z3Rlc3RzXzIwMTMtMjAxNDETMBEGA1UEAxMKTGV2ZWxCQ0FPSzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAIGvQ6Fko2Cezz5ECjNtgVNR3ybvk1uWx438mmZVXrScJahQyr9Ew4KjM79Eujv3sxqCT6/USsmqP7jjFdo/D4B7NTityCgIjymyktblWP7rvhicdIm3S86s+2UdMe49bdPkY1IMWmHeKDhApAwkhY6Csrw+tmUaEWFK7bhMOS7ynpACcIob/v+3LEhc0cXCN7EO3R0RNMAGIwHdn07RNbFrEFvlA7jUSf53+CN2LRTdg6+XOAIaktCIIzxZ00O1lRkQMiYw/T6SBR3cBQKB+qyrlI5blugMhV1epM3e9JguXOa4OCh9/V4gH52+VIVI16R+XBLqW31KhT6uev9He70CAwEAAaOCAl8wggJbMA4GA1UdDwEB/wQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTv6T9dNIdVhUhJ6XvJygfInwSjAzCBzQYDVR0fBIHFMIHCMIG/oIG8oIG5hm9sZGFwOi8veGFkZXNzcnYucGx1Z3Rlc3RzLm5ldC9DTj1MZXZlbEFDQU9LLE9VPVBsdWd0ZXN0c18yMDEzLTIwMTQsTz1FVFNJLEM9RlI/Y2VydGlmaWNhdGVSZXZvY2F0aW9uTGlzdDtiaW5hcnmGRmh0dHA6Ly94YWRlc3Nydi5wbHVndGVzdHMubmV0L3Byb3RlY3RlZC9jYXBzby9jcmxzL1NDT0svTGV2ZWxBQ0FPSy5jcmwwggEmBggrBgEFBQcBAQSCARgwggEUMG8GCCsGAQUFBzAChmNsZGFwOi8veGFkZXNzcnYucGx1Z3Rlc3RzLm5ldC9DTj1MZXZlbEFDQU9LLE9VPVBsdWd0ZXN0c18yMDEzLTIwMTQsTz1FVFNJLEM9RlI/Y0FDZXJ0aWZpY2F0ZTtiaW5hcnkwUwYIKwYBBQUHMAKGR2h0dHA6Ly94YWRlc3Nydi5wbHVndGVzdHMubmV0L3Byb3RlY3RlZC9jYXBzby9jZXJ0cy9TQ09LL0xldmVsQUNBT0suY2VyMEwGCCsGAQUFBzABhkBodHRwOi8veGFkZXNzcnYucGx1Z3Rlc3RzLm5ldC9wcm90ZWN0ZWQvY2Fwc28vT0NTUD9jYT1MZXZlbEFDQU9LMB8GA1UdIwQYMBaAFEZ5HDCgRWzRtQxORNUhmqZ+jzL1MA0GCSqGSIb3DQEBCwUAA4IBAQAj7wSfY8IZh8lByWaf/o9/lTpksakapiqhdXtf/5jqAdaRPPTdIx0kokNl16C1shqgfbCecUhDq+LZ+uQtl/20IH5lXxLdKtlaBV44DTHsbKvKiPBNkWsa80P7jGduaZZeHfQMYAyAtXZonVQAI7lJA7FrwYWmJy5BCt26C5mnwyQBY8QuRZWFZCjZ2STjW9TbsnZ8KFUAcGw3HX1/US07Co+K7ndD5wHHedNum3sc9PldwsH6Q8Hy6nun+B8GTIMHqL55koIsMFlq8dZoB62+QFSqTZ/nAe/HUPdGWT1kMH750ttK3vNB07B1S8WFM6Q448Xz7M0o2Qm/kEDFA8vAMIIFdTCCBF2gAwIBAgIIQe8VddXmIWwwDQYJKoZIhvcNAQELBQAwTTELMAkGA1UEBhMCRlIxDTALBgNVBAoTBEVUU0kxHDAaBgNVBAsME1BsdWd0ZXN0c18yMDEzLTIwMTQxETAPBgNVBAMTCFJvb3RDQU9LMB4XDTEzMTExMzAxMTMxNloXDTE2MTExMzAxMTMxNlowTzELMAkGA1UEBhMCRlIxDTALBgNVBAoTBEVUU0kxHDAaBgNVBAsME1BsdWd0ZXN0c18yMDEzLTIwMTQxEzARBgNVBAMTCkxldmVsQUNBT0swggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC2yPrkS3oVCFhyuZ5+c6FQi6Wh72S5b8YimJ9HjuFwlX4GjDtbaYGNTF9CcsWeWEnyEkLKUNxJass2PK7DJsXZulWXp6q5EYcx/oOcv2PirGo61pok7kFJg+7K+pqmBMMKK7vxUpPN4bnjq+/ih6flIQ00rTgJ3N/ZeewFErCq9LlhEOUAxvHSr5/sQoNFn1t/V+IsV86fJJxFS8u30wpO9K9m48MgXkIwhYTQRwfZUsn07271ecrxnKrP1QuseruNfiLaGoZD3M7jgGWtJnAArWAY9TNkYmenhzHqTfYAZFyNW0WUGQd7lQLx9yS89ZQi5Lwy8UO86e0NeEaKGQijAgMBAAGjggJVMIICUTAOBgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQURnkcMKBFbNG1DE5E1SGapn6PMvUwgckGA1UdHwSBwTCBvjCBu6CBuKCBtYZtbGRhcDovL3hhZGVzc3J2LnBsdWd0ZXN0cy5uZXQvQ049Um9vdENBT0ssT1U9UGx1Z3Rlc3RzXzIwMTMtMjAxNCxPPUVUU0ksQz1GUj9jZXJ0aWZpY2F0ZVJldm9jYXRpb25MaXN0O2JpbmFyeYZEaHR0cDovL3hhZGVzc3J2LnBsdWd0ZXN0cy5uZXQvcHJvdGVjdGVkL2NhcHNvL2NybHMvU0NPSy9Sb290Q0FPSy5jcmwwggEgBggrBgEFBQcBAQSCARIwggEOMG0GCCsGAQUFBzAChmFsZGFwOi8veGFkZXNzcnYucGx1Z3Rlc3RzLm5ldC9DTj1Sb290Q0FPSyxPVT1QbHVndGVzdHNfMjAxMy0yMDE0LE89RVRTSSxDPUZSP2NBQ2VydGlmaWNhdGU7YmluYXJ5MFEGCCsGAQUFBzAChkVodHRwOi8veGFkZXNzcnYucGx1Z3Rlc3RzLm5ldC9wcm90ZWN0ZWQvY2Fwc28vY2VydHMvU0NPSy9Sb290Q0FPSy5jZXIwSgYIKwYBBQUHMAGGPmh0dHA6Ly94YWRlc3Nydi5wbHVndGVzdHMubmV0L3Byb3RlY3RlZC9jYXBzby9PQ1NQP2NhPVJvb3RDQU9LMB8GA1UdIwQYMBaAFPFRtay3g9365aOPmq0HiTe85HXXMA0GCSqGSIb3DQEBCwUAA4IBAQCH8viBUUjKrMNu8MlDOPftdGXqlSAWyI6K86WeVIcE+a+s4l71t1obxGRSH5opk8SyIPVq0kvIW1zvVqK/InMEgF9ncZ75GPwch+Ygg+lPyi61dAxAdhvHvwDm+S1xHaG5MQkKwDcUc1iz3TDsmczJHuikC+VVN+an6EGeDjoVxdEGJsU8P7I+aCdLi1xZNaGkzgfI9fLj5NahJxXi5e4a4reFwm6uJVEJhf0s8cd5At3lSRJlRHTTqIcFkt7hY/YMQwJPKyjoHNqLNaxLl72JanoncGbbNk/qD6A5H9UoDN8LlNaC76a9dvFPi2vMG0Bm7hiZXOxcyzD37B8Gk6ETMIIDXjCCAkagAwIBAgIIbny7ILjGVj0wDQYJKoZIhvcNAQELBQAwTTELMAkGA1UEBhMCRlIxDTALBgNVBAoTBEVUU0kxHDAaBgNVBAsME1BsdWd0ZXN0c18yMDEzLTIwMTQxETAPBgNVBAMTCFJvb3RDQU9LMB4XDTEzMTExMzAxMTMwOFoXDTE3MTExMzAxMTMwOFowTTELMAkGA1UEBhMCRlIxDTALBgNVBAoTBEVUU0kxHDAaBgNVBAsME1BsdWd0ZXN0c18yMDEzLTIwMTQxETAPBgNVBAMTCFJvb3RDQU9LMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkAzE4bbO2hKGSYay+95s5aVQi26o8eLSC04MBM4o2+Ypo9TUxyn7ePbEE2xWHuPhWrBAt3GEaZoB8WnZFiaY3yrc92KzE3XItA3jOMig7TKfiDJiUFz8LRSURNUNf+cf3YSSQZ3bB8M9fg+O2uYjmvViG/Qifj8M6xtmMAcnS0LxIK3RqAc+RGtHKPyUjVwl6TJepK0xejHfsz6DZjtWxd+RK0ELkjX8DH9qlg1qZefB5IJjbRihrKz93oxq2/QpMgNXKENjpzv0VXUntSIMSo6OSMIqrDLDuqDcXUZzdYCFxi1kVkOiWScPOAE3KujOVynUVrYVO2YdG9lrL0AhgQIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU8VG1rLeD3frlo4+arQeJN7zkddcwDQYJKoZIhvcNAQELBQADggEBAFQUCrIRNme3rzf0UnK7x5jRSMazIMYWRdGzgeiHOPNElDbkty+oPgJjk095Kx9kkb0zR79zEAiZ6dd++L7oCpBjttF521dxO/Lxd+stnFi8VHv7oIuRgHT+QG1VovAXCzsqtTePeX6zjZffkioo/mARu86xoStjo/RjcHXEf1TAUloMjmV2N5uHFYqSSNwWFEPEX46FQWaIMpHFSLJTR0k9e3kAkYslzsMtmKLTbFTtmniwN/raFnSbzmK4vcmzT0EeZSd8+PeGQ/8jZMIMXwVjecT2n+pyRhhAQEh0x682Z+1CfdnJwyEaCSvIGIjmVpPJL0fbj8dELWTF2dMPzF4xgiO5MIIjtQIBATBaME8xCzAJBgNVBAYTAkZSMQ0wCwYDVQQKEwRFVFNJMRwwGgYDVQQLDBNQbHVndGVzdHNfMjAxMy0yMDE0MRMwEQYDVQQDEwpMZXZlbEJDQU9LAgcCWJHVJ0yIMAkGBSsOAwIaBQCggfswGAYJKoZIhvcNAQkDMQsGCSqGSIb3DQEHATAcBgkqhkiG9w0BCQUxDxcNMTMxMjA4MTc0NDQzWjAjBgkqhkiG9w0BCQQxFgQUNZD5SeVqggQVm82LnxUQ0AidwRcwgZsGCyqGSIb3DQEJEAIvMYGLMIGIMIGFMIGCBCDKdrd/br3rbeyUPBwAOE+ycRDcZCCrkJWqzFkNZmOYwTBeMFOkUTBPMQswCQYDVQQGEwJGUjENMAsGA1UEChMERVRTSTEcMBoGA1UECwwTUGx1Z3Rlc3RzXzIwMTMtMjAxNDETMBEGA1UEAxMKTGV2ZWxCQ0FPSwIHAliR1SdMiDANBgkqhkiG9w0BAQEFAASCAQBaOQF7tfsT2xf+pSsPN13Qeh9xlH7m1ZVAfzudPzOY4fjL4xb9pTWkCTWTwtgYILoNlTIxhg7qhDH4xBEhSsSclrl24OCWoCGlF7heeCBk7uRwnszcSyts8ca/mD2vRH5w5hFXHCtcv9f064N8hd9qHs/IBcgaDy0/57y6nSkccZJdO4O3QficAzooFwkwafLJbyMlJcB5AW0tq022OBVbc6rrICIwwScXwYRcPB6g9xisc2JdjbdzbfnWQ5pjyEePhgmIIOpfQJITsQaxMPinGVvV0mkXRO+1rSCIGs6vetUgJknok6QV0jR+4H6dl5YmvMhbouUZ6epACjtXJJCIoYIhNjCCAdEGCyqGSIb3DQEJEAIWMYIBwDCCAbwwgZGggY4wgYswgYgwgYUwITAJBgUrDgMCGgUABBT1vN7PEYBpv+VfK1zaX1S/0DVSjTBgME8xCzAJBgNVBAYTAkZSMQ0wCwYDVQQKEwRFVFNJMRwwGgYDVQQLDBNQbHVndGVzdHNfMjAxMy0yMDE0MRMwEQYDVQQDEwpMZXZlbEJDQU9LFw0xMzEyMDgxNTM4MzVaMIGRoIGOMIGLMIGIMIGFMCEwCQYFKw4DAhoFAAQUFKe0/cMtnPFLgka7VmLNmbAVA2wwYDBPMQswCQYDVQQGEwJGUjENMAsGA1UEChMERVRTSTEcMBoGA1UECwwTUGx1Z3Rlc3RzXzIwMTMtMjAxNDETMBEGA1UEAxMKTGV2ZWxBQ0FPSxcNMTMxMjA4MTUzODM1WjCBj6CBjDCBiTCBhjCBgzAhMAkGBSsOAwIaBQAEFCfJ+01BRRzDlU4Boq3WyU68SRJ5MF4wTTELMAkGA1UEBhMCRlIxDTALBgNVBAoTBEVUU0kxHDAaBgNVBAsME1BsdWd0ZXN0c18yMDEzLTIwMTQxETAPBgNVBAMTCFJvb3RDQU9LFw0xMzEyMDgxNTM4MzVaMAAwggIsBgsqhkiG9w0BCRACFTGCAhswggIXMIGDMCEwCQYFKw4DAhoFAAQUW0SBjPUc8ICLSTEJuplvIggflhAwXjBTpFEwTzELMAkGA1UEBhMCRlIxDTALBgNVBAoTBEVUU0kxHDAaBgNVBAsME1BsdWd0ZXN0c18yMDEzLTIwMTQxEzARBgNVBAMTCkxldmVsQkNBT0sCBwJYkdUnTIgwgYQwITAJBgUrDgMCGgUABBQRCFbo13wNMKmsF9X/obkEmlT8CzBfMFOkUTBPMQswCQYDVQQGEwJGUjENMAsGA1UEChMERVRTSTEcMBoGA1UECwwTUGx1Z3Rlc3RzXzIwMTMtMjAxNDETMBEGA1UEAxMKTGV2ZWxBQ0FPSwIIHdVKCKd/MVgwgYIwITAJBgUrDgMCGgUABBTQqxUnem44tk7ziyiuuu7moy6z8DBdMFGkTzBNMQswCQYDVQQGEwJGUjENMAsGA1UEChMERVRTSTEcMBoGA1UECwwTUGx1Z3Rlc3RzXzIwMTMtMjAxNDERMA8GA1UEAxMIUm9vdENBT0sCCEHvFXXV5iFsMIGCMCEwCQYFKw4DAhoFAAQU/I9pAlQYK+6O9KGZgI+b40Oe9R8wXTBRpE8wTTELMAkGA1UEBhMCRlIxDTALBgNVBAoTBEVUU0kxHDAaBgNVBAsME1BsdWd0ZXN0c18yMDEzLTIwMTQxETAPBgNVBAMTCFJvb3RDQU9LAghufLsguMZWPTCCDAUGCyqGSIb3DQEJEAIZMYIL9DCCC/AGCSqGSIb3DQEHAqCCC+EwggvdAgEDMQ8wDQYJYIZIAWUDBAIBBQAwdgYLKoZIhvcNAQkQAQSgZwRlMGMCAQEGDisGAQQBlRICAgUCAQEBMB8wBwYFKw4DAhoEFIh5BIA7NfbVF7hkBMRuds8eDqSzAgcxQl5ZCBxWGA8yMDEzMTIwODE3NDQ0NFowCQIBAYABAYEBAQIIDXrvXXpQ6RygggjaMIIDXjCCAkagAwIBAgIIbny7ILjGVj0wDQYJKoZIhvcNAQELBQAwTTELMAkGA1UEBhMCRlIxDTALBgNVBAoTBEVUU0kxHDAaBgNVBAsME1BsdWd0ZXN0c18yMDEzLTIwMTQxETAPBgNVBAMTCFJvb3RDQU9LMB4XDTEzMTExMzAxMTMwOFoXDTE3MTExMzAxMTMwOFowTTELMAkGA1UEBhMCRlIxDTALBgNVBAoTBEVUU0kxHDAaBgNVBAsME1BsdWd0ZXN0c18yMDEzLTIwMTQxETAPBgNVBAMTCFJvb3RDQU9LMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkAzE4bbO2hKGSYay+95s5aVQi26o8eLSC04MBM4o2+Ypo9TUxyn7ePbEE2xWHuPhWrBAt3GEaZoB8WnZFiaY3yrc92KzE3XItA3jOMig7TKfiDJiUFz8LRSURNUNf+cf3YSSQZ3bB8M9fg+O2uYjmvViG/Qifj8M6xtmMAcnS0LxIK3RqAc+RGtHKPyUjVwl6TJepK0xejHfsz6DZjtWxd+RK0ELkjX8DH9qlg1qZefB5IJjbRihrKz93oxq2/QpMgNXKENjpzv0VXUntSIMSo6OSMIqrDLDuqDcXUZzdYCFxi1kVkOiWScPOAE3KujOVynUVrYVO2YdG9lrL0AhgQIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU8VG1rLeD3frlo4+arQeJN7zkddcwDQYJKoZIhvcNAQELBQADggEBAFQUCrIRNme3rzf0UnK7x5jRSMazIMYWRdGzgeiHOPNElDbkty+oPgJjk095Kx9kkb0zR79zEAiZ6dd++L7oCpBjttF521dxO/Lxd+stnFi8VHv7oIuRgHT+QG1VovAXCzsqtTePeX6zjZffkioo/mARu86xoStjo/RjcHXEf1TAUloMjmV2N5uHFYqSSNwWFEPEX46FQWaIMpHFSLJTR0k9e3kAkYslzsMtmKLTbFTtmniwN/raFnSbzmK4vcmzT0EeZSd8+PeGQ/8jZMIMXwVjecT2n+pyRhhAQEh0x682Z+1CfdnJwyEaCSvIGIjmVpPJL0fbj8dELWTF2dMPzF4wggV0MIIEXKADAgECAgcBqkWS02xhMA0GCSqGSIb3DQEBCwUAME0xCzAJBgNVBAYTAkZSMQ0wCwYDVQQKEwRFVFNJMRwwGgYDVQQLDBNQbHVndGVzdHNfMjAxMy0yMDE0MREwDwYDVQQDEwhSb290Q0FPSzAeFw0xMzExMjkxMzQyNTFaFw0xNTExMjkxMzQyNTFaMEgxCzAJBgNVBAYTAkZSMQ0wCwYDVQQKEwRFVFNJMRwwGgYDVQQLDBNQbHVndGVzdHNfMjAxMy0yMDE0MQwwCgYDVQQDEwNUU0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCFcYT0G09K0J+VkffNbpYA0CnnxNj50qIZJJM4SCkcTFVNGjpMkhzwvFYLkBJDKLkd6VZRWxyzB//uAop0UpN002+7BM+wDxw8ZgJbf6bj6uaEExYsS02PQvbOEnEve4OUHhOgJnkGMvB6vuJG1bjnADM0QNkTnGPHJRXVMEG9ywF1TgKWWspPVAhked06atMr6kxhtSKKEzsQJI9wpSWRcasdQBrhqg7K3tvRHGpuXS8AkdSG04MMs1Riuinx52iYse0PS6fLYXM/ZArd38cXliJi3diyhNOQoQPhrFzbquNlvUSevCOAdLVK4NZI0j/VT5wwsT665Acaw0EaJPoXAgMBAAGjggJcMIICWDAOBgNVHQ8BAf8EBAMCB4AwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwgwHQYDVR0OBBYEFJfqgUFoiCBjZx9JlBHPSs1KLmyjMIHJBgNVHR8EgcEwgb4wgbuggbiggbWGbWxkYXA6Ly94YWRlc3Nydi5wbHVndGVzdHMubmV0L0NOPVJvb3RDQU9LLE9VPVBsdWd0ZXN0c18yMDEzLTIwMTQsTz1FVFNJLEM9RlI/Y2VydGlmaWNhdGVSZXZvY2F0aW9uTGlzdDtiaW5hcnmGRGh0dHA6Ly94YWRlc3Nydi5wbHVndGVzdHMubmV0L3Byb3RlY3RlZC9jYXBzby9jcmxzL1NDT0svUm9vdENBT0suY3JsMIIBIAYIKwYBBQUHAQEEggESMIIBDjBtBggrBgEFBQcwAoZhbGRhcDovL3hhZGVzc3J2LnBsdWd0ZXN0cy5uZXQvQ049Um9vdENBT0ssT1U9UGx1Z3Rlc3RzXzIwMTMtMjAxNCxPPUVUU0ksQz1GUj9jQUNlcnRpZmljYXRlO2JpbmFyeTBRBggrBgEFBQcwAoZFaHR0cDovL3hhZGVzc3J2LnBsdWd0ZXN0cy5uZXQvcHJvdGVjdGVkL2NhcHNvL2NlcnRzL1NDT0svUm9vdENBT0suY2VyMEoGCCsGAQUFBzABhj5odHRwOi8veGFkZXNzcnYucGx1Z3Rlc3RzLm5ldC9wcm90ZWN0ZWQvY2Fwc28vT0NTUD9jYT1Sb290Q0FPSzAfBgNVHSMEGDAWgBTxUbWst4Pd+uWjj5qtB4k3vOR11zANBgkqhkiG9w0BAQsFAAOCAQEAbuMUod0KHhthhxcdx7kaC07pUmKi7MxeusL/hKMitRtGpJ/D5nMnIsk56kszYg0tQAPE7j1BJXGqfdPH8l2l99FN+etgqv4NlA1mAjIdqU38+dDo69vuAtHejpRru+FOW3A8bzkghQiuoudLUXN2p6OGjbaGs2KsxF3PFfCY5jeZd6o1m85P/dhVP6F+9dS2V+3iYUc5I2HXf8nHkaqAcOAm6Q/W82Gmx+EopiwhMNGut7zVG2prJZlauxs7ptYqn1Wimf4xQ5cw7FL+Js2JMoq6QQ6HgD2W6H5wUPxfbLQUVw048ldtUxm8PDcknyIKLv7Cp0u55fXFNY6jt4oByjGCAm8wggJrAgEBMFgwTTELMAkGA1UEBhMCRlIxDTALBgNVBAoTBEVUU0kxHDAaBgNVBAsME1BsdWd0ZXN0c18yMDEzLTIwMTQxETAPBgNVBAMTCFJvb3RDQU9LAgcBqkWS02xhMA0GCWCGSAFlAwQCAQUAoIHpMBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAvBgkqhkiG9w0BCQQxIgQgL/YL6EQuiIA3njhc31xCZD7bYGi5OFl8vkaTE4bJUQMwgZkGCyqGSIb3DQEJEAIvMYGJMIGGMIGDMIGABCDB/np5UxvhcPnSxD2Kme+C88uXGCMWLAvFPHNvTApTWDBcMFGkTzBNMQswCQYDVQQGEwJGUjENMAsGA1UEChMERVRTSTEcMBoGA1UECwwTUGx1Z3Rlc3RzXzIwMTMtMjAxNDERMA8GA1UEAxMIUm9vdENBT0sCBwGqRZLTbGEwDQYJKoZIhvcNAQEBBQAEggEAXNHL7+ut7vvWSuujpzMr2BuW3FDHMUN/T5erBz9BhpRz/AeBwTIR4AeJEclNZL73dxHza2WOS0XPnEBoLW92BA95Wnx3HV111ZwBpSxaMlk5sdLjkMqyN8mcmjz4umI6KjQlrDf6jqTwdu4I+zZxMhC1OaBP6TCZ26IDorpchs8Za1GmIxlwQru8CSausG15H+Wr5P09bQMg3KfXmgJPjk4DTPBeH4Zmu4mEUdyFnU8CpzB1KRNk+EldFW60fgZnOVw6tc62+Q/k6xYZG8sTdSpBs3VZtrUkbnXsqQao+9ikyT4d4s14DR/Q625xLy/0mIBBvJzUBtz8Qz8mRVR61zCCESQGCyqGSIb3DQEJEAIOMYIREzCCEQ8GCSqGSIb3DQEHAqCCEQAwghD8AgEDMQ8wDQYJYIZIAWUDBAIBBQAwdgYLKoZIhvcNAQkQAQSgZwRlMGMCAQEGDisGAQQBlRICAgUCAQEBMB8wBwYFKw4DAhoEFGj8+DK/YyoJ9vc26YqmkXLYGegVAgcxQl5YcpMVGA8yMDEzMTIwODE3NDQ0M1owCQIBAYABAYEBAQIIDXrvXXpQ6RygggjaMIIDXjCCAkagAwIBAgIIbny7ILjGVj0wDQYJKoZIhvcNAQELBQAwTTELMAkGA1UEBhMCRlIxDTALBgNVBAoTBEVUU0kxHDAaBgNVBAsME1BsdWd0ZXN0c18yMDEzLTIwMTQxETAPBgNVBAMTCFJvb3RDQU9LMB4XDTEzMTExMzAxMTMwOFoXDTE3MTExMzAxMTMwOFowTTELMAkGA1UEBhMCRlIxDTALBgNVBAoTBEVUU0kxHDAaBgNVBAsME1BsdWd0ZXN0c18yMDEzLTIwMTQxETAPBgNVBAMTCFJvb3RDQU9LMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkAzE4bbO2hKGSYay+95s5aVQi26o8eLSC04MBM4o2+Ypo9TUxyn7ePbEE2xWHuPhWrBAt3GEaZoB8WnZFiaY3yrc92KzE3XItA3jOMig7TKfiDJiUFz8LRSURNUNf+cf3YSSQZ3bB8M9fg+O2uYjmvViG/Qifj8M6xtmMAcnS0LxIK3RqAc+RGtHKPyUjVwl6TJepK0xejHfsz6DZjtWxd+RK0ELkjX8DH9qlg1qZefB5IJjbRihrKz93oxq2/QpMgNXKENjpzv0VXUntSIMSo6OSMIqrDLDuqDcXUZzdYCFxi1kVkOiWScPOAE3KujOVynUVrYVO2YdG9lrL0AhgQIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU8VG1rLeD3frlo4+arQeJN7zkddcwDQYJKoZIhvcNAQELBQADggEBAFQUCrIRNme3rzf0UnK7x5jRSMazIMYWRdGzgeiHOPNElDbkty+oPgJjk095Kx9kkb0zR79zEAiZ6dd++L7oCpBjttF521dxO/Lxd+stnFi8VHv7oIuRgHT+QG1VovAXCzsqtTePeX6zjZffkioo/mARu86xoStjo/RjcHXEf1TAUloMjmV2N5uHFYqSSNwWFEPEX46FQWaIMpHFSLJTR0k9e3kAkYslzsMtmKLTbFTtmniwN/raFnSbzmK4vcmzT0EeZSd8+PeGQ/8jZMIMXwVjecT2n+pyRhhAQEh0x682Z+1CfdnJwyEaCSvIGIjmVpPJL0fbj8dELWTF2dMPzF4wggV0MIIEXKADAgECAgcBqkWS02xhMA0GCSqGSIb3DQEBCwUAME0xCzAJBgNVBAYTAkZSMQ0wCwYDVQQKEwRFVFNJMRwwGgYDVQQLDBNQbHVndGVzdHNfMjAxMy0yMDE0MREwDwYDVQQDEwhSb290Q0FPSzAeFw0xMzExMjkxMzQyNTFaFw0xNTExMjkxMzQyNTFaMEgxCzAJBgNVBAYTAkZSMQ0wCwYDVQQKEwRFVFNJMRwwGgYDVQQLDBNQbHVndGVzdHNfMjAxMy0yMDE0MQwwCgYDVQQDEwNUU0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCFcYT0G09K0J+VkffNbpYA0CnnxNj50qIZJJM4SCkcTFVNGjpMkhzwvFYLkBJDKLkd6VZRWxyzB//uAop0UpN002+7BM+wDxw8ZgJbf6bj6uaEExYsS02PQvbOEnEve4OUHhOgJnkGMvB6vuJG1bjnADM0QNkTnGPHJRXVMEG9ywF1TgKWWspPVAhked06atMr6kxhtSKKEzsQJI9wpSWRcasdQBrhqg7K3tvRHGpuXS8AkdSG04MMs1Riuinx52iYse0PS6fLYXM/ZArd38cXliJi3diyhNOQoQPhrFzbquNlvUSevCOAdLVK4NZI0j/VT5wwsT665Acaw0EaJPoXAgMBAAGjggJcMIICWDAOBgNVHQ8BAf8EBAMCB4AwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwgwHQYDVR0OBBYEFJfqgUFoiCBjZx9JlBHPSs1KLmyjMIHJBgNVHR8EgcEwgb4wgbuggbiggbWGbWxkYXA6Ly94YWRlc3Nydi5wbHVndGVzdHMubmV0L0NOPVJvb3RDQU9LLE9VPVBsdWd0ZXN0c18yMDEzLTIwMTQsTz1FVFNJLEM9RlI/Y2VydGlmaWNhdGVSZXZvY2F0aW9uTGlzdDtiaW5hcnmGRGh0dHA6Ly94YWRlc3Nydi5wbHVndGVzdHMubmV0L3Byb3RlY3RlZC9jYXBzby9jcmxzL1NDT0svUm9vdENBT0suY3JsMIIBIAYIKwYBBQUHAQEEggESMIIBDjBtBggrBgEFBQcwAoZhbGRhcDovL3hhZGVzc3J2LnBsdWd0ZXN0cy5uZXQvQ049Um9vdENBT0ssT1U9UGx1Z3Rlc3RzXzIwMTMtMjAxNCxPPUVUU0ksQz1GUj9jQUNlcnRpZmljYXRlO2JpbmFyeTBRBggrBgEFBQcwAoZFaHR0cDovL3hhZGVzc3J2LnBsdWd0ZXN0cy5uZXQvcHJvdGVjdGVkL2NhcHNvL2NlcnRzL1NDT0svUm9vdENBT0suY2VyMEoGCCsGAQUFBzABhj5odHRwOi8veGFkZXNzcnYucGx1Z3Rlc3RzLm5ldC9wcm90ZWN0ZWQvY2Fwc28vT0NTUD9jYT1Sb290Q0FPSzAfBgNVHSMEGDAWgBTxUbWst4Pd+uWjj5qtB4k3vOR11zANBgkqhkiG9w0BAQsFAAOCAQEAbuMUod0KHhthhxcdx7kaC07pUmKi7MxeusL/hKMitRtGpJ/D5nMnIsk56kszYg0tQAPE7j1BJXGqfdPH8l2l99FN+etgqv4NlA1mAjIdqU38+dDo69vuAtHejpRru+FOW3A8bzkghQiuoudLUXN2p6OGjbaGs2KsxF3PFfCY5jeZd6o1m85P/dhVP6F+9dS2V+3iYUc5I2HXf8nHkaqAcOAm6Q/W82Gmx+EopiwhMNGut7zVG2prJZlauxs7ptYqn1Wimf4xQ5cw7FL+Js2JMoq6QQ6HgD2W6H5wUPxfbLQUVw048ldtUxm8PDcknyIKLv7Cp0u55fXFNY6jt4oByjGCB44wggeKAgEBMFgwTTELMAkGA1UEBhMCRlIxDTALBgNVBAoTBEVUU0kxHDAaBgNVBAsME1BsdWd0ZXN0c18yMDEzLTIwMTQxETAPBgNVBAMTCFJvb3RDQU9LAgcBqkWS02xhMA0GCWCGSAFlAwQCAQUAoIHpMBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAvBgkqhkiG9w0BCQQxIgQgy2wd0uond5EsNNuJSh3PuwwRjU7/8xv1ZC1hzs1dbrowgZkGCyqGSIb3DQEJEAIvMYGJMIGGMIGDMIGABCDB/np5UxvhcPnSxD2Kme+C88uXGCMWLAvFPHNvTApTWDBcMFGkTzBNMQswCQYDVQQGEwJGUjENMAsGA1UEChMERVRTSTEcMBoGA1UECwwTUGx1Z3Rlc3RzXzIwMTMtMjAxNDERMA8GA1UEAxMIUm9vdENBT0sCBwGqRZLTbGEwDQYJKoZIhvcNAQEBBQAEggEAAxjxQRCvVMrR77fut0Pfm8Dk1yojMhfKEDtteB5zTLxJs1Eighne90lEc0Th5qQ5RZsYiGXLrW0TqEenonR0fff4xZA9T2FM35jVUxJH9wTf8dDzxC6mFHrs0FMNBr1WGHaM+dCDYnVmxLA2g54I6I8YF+glwpMusWHVsapvDJ6p/kB/PpsYe0musexxSiyQs0CFhznmWK02NfU/nJuq4o/Zr3KfZwaSFVMh4QAtzGvr6E13XeQxl21ZzU17vnz+coQoV9oHv6k2HRlIr8Q4kb/bsNicLcCtbsKxf4hljxuXZb4r60coceGK+nR1a13GYGwLiV29Af1jAKDrHp/Ba6GCBRswggJjBgsqhkiG9w0BCRACFjGCAlIwggJOMIGRoIGOMIGLMIGIMIGFMCEwCQYFKw4DAhoFAAQU9bzezxGAab/lXytc2l9Uv9A1Uo0wYDBPMQswCQYDVQQGEwJGUjENMAsGA1UEChMERVRTSTEcMBoGA1UECwwTUGx1Z3Rlc3RzXzIwMTMtMjAxNDETMBEGA1UEAxMKTGV2ZWxCQ0FPSxcNMTMxMjA4MTUzODM1WjCBkaCBjjCBizCBiDCBhTAhMAkGBSsOAwIaBQAEFBSntP3DLZzxS4JGu1ZizZmwFQNsMGAwTzELMAkGA1UEBhMCRlIxDTALBgNVBAoTBEVUU0kxHDAaBgNVBAsME1BsdWd0ZXN0c18yMDEzLTIwMTQxEzARBgNVBAMTCkxldmVsQUNBT0sXDTEzMTIwODE1MzgzNVowgY+ggYwwgYkwgYYwgYMwITAJBgUrDgMCGgUABBQnyftNQUUcw5VOAaKt1slOvEkSeTBeME0xCzAJBgNVBAYTAkZSMQ0wCwYDVQQKEwRFVFNJMRwwGgYDVQQLDBNQbHVndGVzdHNfMjAxMy0yMDE0MREwDwYDVQQDEwhSb290Q0FPSxcNMTMxMjA4MTUzODM1WjAAMIGPoIGMMIGJMIGGMIGDMCEwCQYFKw4DAhoFAAQUJ8n7TUFFHMOVTgGirdbJTrxJEnkwXjBNMQswCQYDVQQGEwJGUjENMAsGA1UEChMERVRTSTEcMBoGA1UECwwTUGx1Z3Rlc3RzXzIwMTMtMjAxNDERMA8GA1UEAxMIUm9vdENBT0sXDTEzMTIwODE1MzgzNVowggKwBgsqhkiG9w0BCRACFTGCAp8wggKbMIGDMCEwCQYFKw4DAhoFAAQUW0SBjPUc8ICLSTEJuplvIggflhAwXjBTpFEwTzELMAkGA1UEBhMCRlIxDTALBgNVBAoTBEVUU0kxHDAaBgNVBAsME1BsdWd0ZXN0c18yMDEzLTIwMTQxEzARBgNVBAMTCkxldmVsQkNBT0sCBwJYkdUnTIgwgYQwITAJBgUrDgMCGgUABBQRCFbo13wNMKmsF9X/obkEmlT8CzBfMFOkUTBPMQswCQYDVQQGEwJGUjENMAsGA1UEChMERVRTSTEcMBoGA1UECwwTUGx1Z3Rlc3RzXzIwMTMtMjAxNDETMBEGA1UEAxMKTGV2ZWxBQ0FPSwIIHdVKCKd/MVgwgYIwITAJBgUrDgMCGgUABBTQqxUnem44tk7ziyiuuu7moy6z8DBdMFGkTzBNMQswCQYDVQQGEwJGUjENMAsGA1UEChMERVRTSTEcMBoGA1UECwwTUGx1Z3Rlc3RzXzIwMTMtMjAxNDERMA8GA1UEAxMIUm9vdENBT0sCCEHvFXXV5iFsMIGCMCEwCQYFKw4DAhoFAAQU/I9pAlQYK+6O9KGZgI+b40Oe9R8wXTBRpE8wTTELMAkGA1UEBhMCRlIxDTALBgNVBAoTBEVUU0kxHDAaBgNVBAsME1BsdWd0ZXN0c18yMDEzLTIwMTQxETAPBgNVBAMTCFJvb3RDQU9LAghufLsguMZWPTCBgTAhMAkGBSsOAwIaBQAEFKSOdK+W1ZjwRinz0E7ByO/2xv5cMFwwUaRPME0xCzAJBgNVBAYTAkZSMQ0wCwYDVQQKEwRFVFNJMRwwGgYDVQQLDBNQbHVndGVzdHNfMjAxMy0yMDE0MREwDwYDVQQDEwhSb290Q0FPSwIHAapFktNsYQ==");

		// tag::cmsDocument[]
		// import eu.europa.esig.dss.cades.signature.CMSSignedDocument;
		// import eu.europa.esig.dss.model.DSSDocument;
		// import org.bouncycastle.cms.CMSSignedData;

		// Instantiate a CMSSignedDocument from a CMSSignedData
		CMSSignedData cmsSignedData = new CMSSignedData(cmsBytes);
		DSSDocument fileDocument = new CMSSignedDocument(cmsSignedData);

		// end::cmsDocument[]

		assertNotNull(fileDocument.getDigestValue(DigestAlgorithm.SHA256));

		try (InputStream is = fileDocument.openStream()) {
			// expected behavior
		} catch (UnsupportedOperationException | IOException e) {
			fail("Cannot open an InMemoryDocument");
		}

	}

	@Test
	void testContainerEntryDocument() {

		// tag::containerEntryDocument[]
		// import eu.europa.esig.dss.asic.common.ContainerEntryDocument;
		// import eu.europa.esig.dss.model.DSSDocument;
		// import eu.europa.esig.dss.model.FileDocument;
		// import eu.europa.esig.dss.asic.common.DSSZipEntry;
		// import java.util.zip.ZipEntry;

		// Get an instance of DSSDocument
		DSSDocument document = new FileDocument("src/main/resources/xml_example.xml");

		// Instantiate a DSSZipEntry
		// NOTE: the name of the document and zipEntry SHALL be the same
		DSSZipEntry zipEntry = new DSSZipEntry(document.getName());

		// Define metadata (optional)
		zipEntry.setComment("Nowina Solutions");
		zipEntry.setCompressionMethod(ZipEntry.DEFLATED);
		zipEntry.setCreationTime(new Date());

		// Instantiate a ContainerEntryDocument
		DSSDocument containerEntryDocument = new ContainerEntryDocument(document, zipEntry);

		// end::containerEntryDocument[]

		assertNotNull(containerEntryDocument.getDigestValue(DigestAlgorithm.SHA256));

		try (InputStream is = containerEntryDocument.openStream()) {
			// expected behavior
		} catch (UnsupportedOperationException | IOException e) {
			fail("Cannot open an InMemoryDocument");
		}

	}

	@Test
	void httpHeaderDocument() {

		// tag::httpHeader[]
		// import eu.europa.esig.dss.jades.HTTPHeader;
		// import eu.europa.esig.dss.jades.HTTPHeaderDigest;
		// import eu.europa.esig.dss.model.DSSDocument;
		// import eu.europa.esig.dss.model.InMemoryDocument;

		// An HTTPHeader shall be defined with a header name and a value
		DSSDocument httpHeader = new HTTPHeader("content-type", "application/json");

		// An `digest` HTTP Header can be created from an HTTP body message, using a DSSDocument and a desired DigestAlgorithm
		DSSDocument httpBodyMessage = new InMemoryDocument("Hello World!".getBytes());
		DSSDocument httpHeaderDigest = new HTTPHeaderDigest(httpBodyMessage, DigestAlgorithm.SHA256);

		// end::httpHeader[]

		try {
			httpHeader.getDigestValue(DigestAlgorithm.SHA256);
			fail("getDigest(...) method is not supported for HTTPHeader document");
		} catch (UnsupportedOperationException e) {
			// normal behavior
		}

		try {
			httpHeaderDigest.getDigestValue(DigestAlgorithm.SHA256);
			fail("getDigest(...) method is not supported for HTTPHeader document");
		} catch (UnsupportedOperationException e) {
			// normal behavior
		}

		try (InputStream is = httpHeader.openStream()) {
			fail("Cannot open a HTTPHeader");
		} catch (UnsupportedOperationException | IOException e) {
			// normal behavior
		}
		try (InputStream is = httpHeaderDigest.openStream()) {
			fail("Cannot open a HTTPHeaderDigest");
		} catch (UnsupportedOperationException | IOException e) {
			// normal behavior
		}

	}

}
