:sectnums:
:sectnumlevels: 5
:sourcetestdir: ../../../test/java
:samplesdir: ../_samples
:imagesdir: images/

[[AdvancedConcepts]]
== Advanced DSS java concepts

[[ServiceLoaderAdvanced]]
=== ServiceLoader
DSS incorporates modules that are loaded in the run time based on the chosen configuration and the input data via a https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html[ServiceLoader]. This provides a flexibility for an end-user to work only with selected modules and a possibility to expand DSS with custom implementations.

In order to provide a chosen implementation(s) to ServiceLoader, a file listing all the desired implementations should be created in the resource directory `META-INF/services` with a name matching the implemented interface. When merging sources (e.g. creating a Fat JAR module), the files can be lost/overwritten, and should be configured manually (all the required implementations shall be listed).

NOTE: If a DSS module(s) implementing a required interface(s) is added to your project's dependency list, the implementation shall be loaded automatically.

The following modules are provided with independent implementations:

* DSS Utils;
* DSS CRL Parser;
* DSS PAdES.

WARNING: If no appropriate available implementation is found, an exception will be thrown.


[[dssUtils]]
==== DSS Utils

The module dss-utils offers an interface with utility methods to operate on String, Collection, I/O,... DSS framework provides two different implementations with the same behaviour :

* dss-utils-apache-commons : this module uses Apache Commons libraries (commons-lang3, commons-collection4, commons-io and commons-codec).
* dss-utils-google-guava : this module only requires Google Guava (recommended on Android).

If your integration include dss-utils, you will need to select an implementation.

[[dssCrlParser]]
==== DSS CRL Parser

DSS contains two ways to parse/validate a CRL and to retrieve revocation data. An alternative to the X509CRL java object was developed to face memory issues in case of large CRLs. The X509CRL object fully loads the CRL in memory and can cause OutOfMemoryError.

* dss-crl-parser-x509crl : this module uses the X509CRL java object.
* dss-crl-parser-streams : this module offers an alternative with a CRL streaming (experimental).

If your integration require dss-crl-parser, you will need to choose your implementation.

[[dssPades]]
==== DSS PAdES

Since the version 5.4, DSS allows generation/extension/validation PAdES signatures with two different frameworks : PDFBox and OpenPDF (fork of iText). The dss-pades module only contains the common code and requires an underlying implementation :

* dss-pades-pdfbox : Supports drawing of custom text, images, as well as text+image, in a signature field.
* dss-pades-openpdf : Supports drawing of custom text OR images in a signature field.

DSS permits to override the visible signature generation with these interfaces :

* eu.europa.esig.dss.pdf.IPdfObjFactory
* eu.europa.esig.dss.pdf.visible.SignatureDrawerFactory (selects the SignatureDrawer depending on the SignatureImageParameters content)
* eu.europa.esig.dss.pdf.visible.SignatureDrawer

A new instance of the IPdfObjFactory can be created with its own SignatureDrawerFactory and injected in the padesService.setPdfObjFactory(IPdfObjFactory). By default, DSS uses an instance of ServiceLoaderPdfObjFactory. This instance checks for any registered implementation in the classpath with the ServiceLoader (potentially a service from dss-pades-pdfbox, dss-pades-openpdf or your own(s)).

===== DSS PDFBox

Since the version 5.5, DSS allows switching between two implementations of the framework PDFBox : default (original) and native.

* Default Drawer : The original drawer implemented on the PDFBox framework, supports displaying of custom text, images, text+image combination in a signature field. The implementation does not include the provided custom text to the inner PDF structure, instead of it, the drawer creates an image representation of the provided text, which is added to the signature field (i.e. the text is not selectable and not searchable).
* Native Drawer : Since the version 5.5, DSS includes a new implementation of PDFBox Drawer, that allows a user to add a real custom text, image or combination of text and image to a visible signature field. The native implementation embeds the provided custom text to the inner PDF structure, that makes the text selectable and searchable, and also clearer and smoother in comparison with the original implementation.

By default, DSS uses "Default Drawer" as the PDFBox implementation. In order to switch the implementation, that allowed in runtime, you have to set a new instance for PdfObjFactory as following:

[source,java,indent=0]
.Runtime PDF Object Factory changing
----
include::{sourcetestdir}/eu/europa/esig/dss/cookbook/example/sign/SignPdfPadesBVisibleTest.java[tags=custom-factory]
----






=== Multithreading

DSS can be used in multi-threaded environments but some points need to be considered like resources sharing and caching. All operations are stateless and this fact requires to be maintained. Some resources can be shared, others are proper to an operation.

For each provided operation, DSS requires a CertificateVerifier object. This object is responsible to provide certificates and accesses to external resources (AIA, CRL, OCSP,...). At the beginning of all operation, CertificateSources and RevocationSources are created for each signature / timestamp / revocation data. Extracted information are combined with the configured sources in the CertificateVerifier. For these reasons, integrators need to be careful about the CertificateVerifier configuration.

==== Resource sharing

The trusted certificates can be shared between multiple threads because these certificates are static. This means they don't require more analysis. Their status won't evolve. For these certificates, DSS doesn't need to collect issuer certificate and/or their revocation data.

In opposition, the adjunct certificates cannot be shared. These certificates concern a specific signature/validation operation. This parameter is used to provide missing certificate(s). When DSS is unable to build the complete certificate path with the provided certificates (as signature parameters or embedded within a signature), it is possible to inject certificates that are not present. These certificates are not necessarily trusted and may require future "modifications" like revocation data collection,...

==== Caching

In case of multi-threading usage, we strongly recommend caching of external resources. All external resources can be cached (AIA, CRL, OCSP) to improve performances and to avoid requesting too much time the same resources. FileCacheDataLoader and JdbcCacheCRLSource can help you in this way.

See section <<CachingUseCases>> of the <<Annex>> for complete examples of caching revocation data, certificates and trusted lists.

=== JAXB modules
==== General
Since the version 5.5, DSS provides the following JAXB modules with a harmonized structure :

* `dss-policy-jaxb` - defines validation policy JAXB model
* `dss-diagnostic-jaxb` - defines Diagnostic Data JAXB model
* `dss-detailed-report-jaxb` - defines Detailed Report JAXB model
* `dss-simple-report-jaxb` - defines Simple Report JAXB model
* `dss-simple-certificate-report-jaxb` - defines Certificate Simple Report JAXB model

All modules share the same logic and have the following structure (where &#42;&#42;&#42; is a model name):

`*_dss-&#42;&#42;&#42;-jaxb_*`::
`*_src/main/java_*`:::
`*_eu.europa.esig.dss.&#42;&#42;&#42;_*`::::
** `*_&#42;&#42;&#42;.java_*` - wrapper(s) which eases the JAXB manipulation
** `*_..._*`
** `*_&#42;&#42;&#42;Facade.java_*` - class which allows marshalling/unmarshalling of jaxb objects, generation of HTML/PDF content, etc.
** `*_&#42;&#42;&#42;XmlDefiner.java_*` - class which contains the model definition (XSD, XSLT references, ObjectFactory)
** `*_jaxb_*` - generated on compile time
*** `*_Xml&#42;&#42;&#42;.java_*` - JAXB model
*** `*_..._*`
`*_src/main/resources_*`:::
`*_xsd_*`::::
** `*_&#42;&#42;&#42;.xsd_*` - XML Schema (XSD) for the Detailed Report model
** `*_binding.xml_*` - XJC instructions to generate the JAXB model from the XSD
`*_xslt_*`::::
** `*_html_*`
*** 	`*_&#42;&#42;&#42;.xslt_*` - XML Stylesheet for the HTML generation
** `*_pdf_*`
***	`*_&#42;&#42;&#42;.xslt_*` - XML Stylesheet for the PDF generation

In the main classes, a `Facade` is present to quickly operate with the JAXB objects (eg: marshall, unmarshall, generate the HTML/PDF, validate the XML structure,...).

[source,java,indent=0]
.DetailedReportFacade usage
----
include::{sourcetestdir}/eu/europa/esig/dss/cookbook/example/snippets/SignedDocumentValidatorTest.java[tags=demo-facade]
----

An `XmlDefiner` is also available with the access to the embedded XML Schemas (XSD), the XML Stylesheets (XSLT) to be able to generate the HTML or the PDF content (for DSS specific JAXB) and the JAXB Object Factory.

[source,java,indent=0]
.DetailedReportXmlDefiner usage
----
include::{sourcetestdir}/eu/europa/esig/dss/cookbook/example/snippets/SignedDocumentValidatorTest.java[tags=demo-xml-definer]
----

==== Creating a trusted list
Below is an example of how to use JAXB modules to create a trusted list

!!! TODO: create and add example

[source,java,indent=0]
.Creation of a trusted list
----
include::
----


==== Validating XSD conformity
Below is an example of how to use JAXB modules to validate the XSD conformity

!!! TODO: create and add example

[source,java,indent=0]
.Validating XSD conformity
----
include::
----



[[ReportStylesheets]]
==== Report stylesheets

The report modules (namely: `dss-simple-report-jaxb`, `dss-simple-certificate-report-jaxb` and `dss-detailed-report-jaxb`) contain two XSLT style sheets each for final reports generation:

* Bootstrap 4 XSLT for HTML report;
* PDF XSLT for PDF report.

NOTE: Since DSS 5.9 only Bootstrap 4 XSLT is provided within the framework for HTML report generation.

In order to generate a report with a selected style sheet you need to call a relevant method in a Facade class (see classes definition above):

[source,java,indent=0]
.HTML report generation
----
include::{sourcetestdir}/eu/europa/esig/dss/cookbook/example/snippets/StylesheetSnippet.java[tags=demo]
----

Otherwise, in case if you need to customize the transformer, you can create a report by using an XmlDefiner:

[source,java,indent=0]
.Custom report generation
----
include::{sourcetestdir}/eu/europa/esig/dss/cookbook/example/snippets/StylesheetSnippet.java[tags=custom]
----




[[xmlSecurities]]
=== XML securities

Since DSS 5.7, the framework allows custom configuration of XML-related modules for enabling/disabling of XML securities (e.g. in order to use Xalan or Xerces).

WARNING: We strongly do not recommend disabling of security features and usage of deprecated dependencies. Be aware: the feature is designed only for experienced users, and all changes made in the module are at your own risk.

The configuration is available for the following classes:

* `javax.xml.parsers.DocumentBuilderFactory` with a `DocumentBuilderFactoryBuilder` - builds a DOM document object from the obtained XML file and creates a new Document;
* `javax.xml.transform.TransformerFactory` with a `TransformerFactoryBuilder` - loads XML templates and builds DOM objects;
* `javax.xml.validation.SchemaFactory` with a `SchemaFactoryBuilder` - loads XML Schema;
* `javax.xml.validation.Validator` with a `ValidatorConfigurator` - configures a validator to validate an XML document against an XML Schema.

All the classes can be configured with the following methods (example for `TransformerFactory`):

[source,java,indent=0]
.XMLSecurities configuration
----
include::{sourcetestdir}/eu/europa/esig/dss/cookbook/example/snippets/XMLSecuritiesConfigTest.java[tags=demo]
----

The `javax.xml.parsers.DocumentBuilderFactory`, that allows XML files parsing and creation of DOM `Document` object, can be configured with the following methods:

NOTE: Since DSS 5.9 the configuration of `javax.xml.parsers.DocumentBuilderFactory` has been moved from `DomUtils` to a new singleton class `DocumentBuilderFactoryBuilder`.

[source,java,indent=0]
.DocumentBuilderFactory configuration
----
include::{sourcetestdir}/eu/europa/esig/dss/cookbook/example/snippets/XMLSecuritiesConfigTest.java[tags=dbf]
----

The class `XmlDefinerUtils` is a singleton, therefore all changes performed on the instance will have an impact to all calls of the related methods.

See section <<Alerts>> in chapter <<Annex>> for more information on alerts.