:sectnums:
:sectnumlevels: 5
:sourcetestdir: ../../../test/java
:samplesdir: ../_samples
:imagesdir: ../images/

[[DSSUpgrades]]
== DSS upgrades and change history

=== Release notes
[cols="1,2,7"]
.Release notes
|===
|Version           |Release date             |Features

|v5.11             |October 2022              a|Main new features / improvements :

                                            * PAdES : improved PDF-signing performance (add caching of the temporary revision);
                                            * PAdES : introduce temporary document processing factory (e.g. in-file or in-memory);
                                            * PAdES : simplified configuration of modification detection modules;
                                            * PAdES : added signing app name for signature;
                                            * ASiC : introduce ASiC Merger;
                                            * ASiC : improved ASiC in-file processing (avoid loading document into memory);
                                            * XAdES : add support of a custom CommitmentType qualifier;
                                            * CAdES : improved signature file extension naming;
                                            * TL-validation : Trust Service equivalence scheme and Mutual Recognition Agreement support;
                                            * Other : dependencies update (Apache Santuario, PdfBox, OpenPdf, httpclient5, etc.);
                                            * Demo : eSignature Validation Test Cases automated validation module;
                                            * Demo : added ASiC Merger webpage;
                                            * Standalone app : add TL signing function;
                                            * Standalone app : add XMLManifest signing function;
                                            * Java 18 support.

|v5.11             |October 2022              a|Bug fixes :

                                            * Qualification determination : Improved algorithm to comply with TS 119 615 + fixed issues;
                                            * JAdES : signature can be created with ECDSA algorithm using a wrong elliptic curve;
                                            * LTA signature is indeterminate because no revocations lists found;
                                            * Exception when a not supported encryption algorithm is provided;
                                            * Validation for ASiC without mimetype returns FORMAT_FAILURE;
                                            * Skipped AcceptableRevocationDataFound constraint may lead to false positive validation result;
                                            * ASiC : unable to proceed validation of CEN-header invalid files;
                                            * SimpleReport : fix valid signatures counter;
                                            * Demo : fix proxy configuration conversion.

|v5.10.1           |April 2022              a|Bug fixes :

                                              * ASiC-E with XAdES parallel signature creation regression;
                                              * ASiC OpenDocument does not sign mimetype and manifest;
                                              * PdfBox : avoid float conversion from COSNumber class;
                                              * JAdES Certificate Source wrong behaviour in method getKeyIdentifierCertificates;
                                              * Upgrade jackson-binding dependency;
                                              * Demo : NPE on PAdES sign;
                                              * Demo : upgrade Spring.

|v5.10             |March 2022              a|Main new features / improvements :

                                              * Cookbook update;
                                              * PAdES : object modification detection;
                                              * PAdES : visual signature preview;
                                              * PAdES : avoid repeated creation of OCSP/CRL tokens;
                                              * PAdES : enforce signature creation/validation against ISO 32 000 restrictions (DocMDP, Lock, etc.);
                                              * PAdES : add validation data on timestamp method (including data for standalone timestamps);
                                              * XAdES and CAdES : added support of extended profiles on validation;
                                              * ASiC services refactoring (various improvements);
                                              * WebService to sign a Trusted List;
                                              * Apple KeyStore as a signature token connection;
                                              * ED448 signature algorithm support;
                                              * Revocation check on B/T-level signature creation;
                                              * Added supportive information to Status object in alerts;
                                              * Same instance of signature parameters can be used for multiple signing operation;
                                              * Demo : new viewer for XML reports (i.e. for DiagnosticData and ETSI VR);
                                              * Dependencies upgrade (HttpClient5, BouncyCastle, Santuario, logback, etc.);
                                              * Java 17 support.

|v5.10             |March 2022              a|Bug fixes :

                                              * PAdES : erroneously triggered visual signature difference warning;
                                              * PAdES : wrong LT-/LTA-level determination for documents with multiple signatures;
                                              * PAdES : original documents extraction does not work against carriage return;
                                              * XAdES : NPE on validation of XAdES v.1.1.1, 1.2.2;
                                              * CAdES : NPE on signature validation without signing-certificate;
                                              * CAdES : counter-signature produces duplicates of existing counter-signatures;
                                              * JAdES : wrong payload computation for 'sigD' with ObjectIdByURI mechanism;
                                              * ASiC : MimeType is lost on re-signature;
                                              * Signature policy caching issue;
                                              * Revocation freshness checks use different values across the code;
                                              * Demo : jumping rows on collapse of TL-validation table;
                                              * Demo : inability to sign when encryption algorithm of the token is different from the one used in signature;
                                              * Demo : wrong encoding on uploaded filenames containing non-ASCII characters.


|v5.9           |September 2021             a|Main new features / improvements :

                                              * Many improvements in the validation reports;
                                              * AIASource introduction : more customizations;
                                              * Customization of revocation collection strategy (OCSP/CRL first);
                                              * DocumentBuilderFactory securities;
                                              * ECDSA / ECDSA-PLAIN support;
                                              * JAdES (JSON AdES) consolidations;
                                              * PAdES visual signature refactorings / improvements :
                                              ** Image scaling : STRETCH / ZOOM_AND_CENTER / CENTER;
                                              ** Text wrapping : BOX_FILL / FILL_BOX_AND_LINEBREAK / FONT_BASIC.
                                              * Dependency upgrades (Santuario, BouncyCastle, PDFBox,…);
                                              * Java 16 support.

Bug fixes :

                                              * Short term OCSP response;
                                              * On hold certificate;
                                              * Qualification conflict (issuance time / best signing time);
                                              * ASiC-S can’t be timestamped twice;
                                              * PAdES revision extraction;
                                              * PAdES wrong level detection (files with multiple signatures/timestamps);
                                              * ETSI Validation report : multiple files / references.

|v5.8           |February 2021                a| * JAdES implementation (ETSI TS 119 182 v0.0.6) : signature creation, extension and validation (advanced electronic signatures based on JWS);
                                               * PDF Shadow attacks : prevention and detection;
                                               * Counter Signature creation (CAdES, XAdES, JAdES and ASiC containers);
                                               * Support of the unsigned attribute SignaturePolicyStore (CAdES, XAdES, JAdES and ASiC containers);
                                               * Support of the QCLimitValue attribute;
                                               * Support of Java 8 up to 15.

|v5.7        |August 2020                     a| * CertificatePool removal and performance amelioration;
                                               * QWAC validator;
                                               * New design of PDF reports;
                                               * Support of PSD2 attributes;
                                               * Support of EdDSA;
                                               * Signature representation with a timeline;
                                               * Visual signature creation with REST/SOAP webservices.

|v5.6        |March 2020                     a| * Complete rewriting of the TL/LOTL loading with:
                                               ** online / offline refresh;
                                               ** 3 caches (download / parse / validate);
                                               ** multiple LOTL support;
                                               ** multiple TL support (not linked to a LOTL);
                                               ** Pivot LOTL support;
                                               ** Synchronization strategy (eg : expired TL/LOTL are rejected/accepted);
                                               ** multi-lingual support (trust service matching);
                                               ** alerting (eg : LOTL/OJ location desynchronization,...);
                                               ** complete reporting (summary of download / parsing / validation).
                                               * Independent timestamp creation and validation (not linked to a signature, with ASiC and PDF);
                                               * Timestamp qualification;
                                               * Internationalization of the validation reports;
                                               * Multiple Trusted Sources support;
                                               * XAdES support of different prefixes / versions.

|v5.5            |October 2019                a| * The implementation of the ETSI Validation Report;
                                               * The support of Java 12 (multi-release jars);
                                               * Webservice which allows to validate certificates.

|v5.4.3          |August 2019                a| * Hotfix release.

|v5.4            |January 2019               a| * Augmentation of signatures with invalid time-stamps, archive-time-stamps and revoked certificates;
                                               * Upgrade to Java 8 or 9;
                                               * Certify documents;
                                               * Add support of KeyHash in OCSP Responses.

|v5.3.2        |October 2018                a| * Security patch, following a security assessment from the Ruhr-Universität Bochum.

|v5.3.1        |July 2018                   a| * Certificate validation;
                                               * content-timestamps generation;
                                               * SHA-3 support;
                                               * non-EU trusted list(s) support;
                                               * integration of the last version of MOCCA.

|v5.3          |May 2018                    a| * Certificate validation;
                                               * content-timestamps generation;
                                               * SHA-3 support;
                                               * non-EU trusted list(s) support;
                                               * integration of the last version of MOCCA.

|v5.2.1        |October 2018                a| * Security patch, following a security assessment from the Ruhr-Universität Bochum.

|v5.2          |December 2017               a| * Qualification matrix guidelines and documentation;
                                               * Improvements regarding visual representation of a signature;
                                               * Alternative packaging: Image docker / spring-boot;
                                               * CRL streaming, the demo won’t use the X509CRL java object by default (it can be changed). With some signatures, we had large CRLs (+60Mo in Estonia) and that could cause memory issues.
                                               * RSASSA-PSS support, I received some requests to support these algorithms :
                                               ** SHA1withRSAandMGF1;
                                               ** SHA224withRSAandMGF1;
                                               ** SHA256withRSAandMGF1;
                                               ** SHA384withRSAandMGF1;
                                               ** SHA512withRSAandMGF1.

|v5.1               |September 2017           a| * Webservices for Server signing REST and SOAP;
                                                 * PAdES : Support of signature fields;
                                                 * PAdES : distinction of PAdES and PKCS7 signatures;
                                                 * Proxy configuration fix.

|v5.0               |April 2017               a| * Refactoring of ASiC format handling, following the ETSI ASiC Plugtest;
                                               * Signature of multiple files (ASiC and XAdES);
                                               * Integration of the Qualification matrix as described in draft ETSI 119 172-4, for supporting signatures before and after 01/07/2016 (eIDAS entry into force);
                                               * Migration to PDFBox 2 for handling PDFs.
                                               * Complete refactoring of the ASiC part (creation, extension and validation);
                                               * Compliance to eIDAS regulation.

|v4.7               |October 2016             a|A XAdES PlugTest is planned in October / November 2015. Remaining changes resulting from this PlugTest and not included in v4.6 may be included in this release.
An eSignature Validation PlugTest is planned in April 2016. Depending on the actual timeframe, impacts from this PlugTest may be included in this release, and the release of DSS 4.7 will be postponed accordingly.

Other potential improvements and features:

                                               * Extension of signature validation policy support;
                                               * CAdES attribute certificates;
                                               * CRL in multiple parts;
                                               * Distributed timestamps method;
                                               * Support of cross-certification in path building.

|v4.6*           |March 2016                a| Based on standards:

                                               * Signature formats when creating a signature: baseline profiles ETSI TS 103 171, 103 172, 103 173, and 103 174;
                                               * Signature formats when validating a signature: baseline profiles, and core specs ETSI TS 101 903, 101 733, 102 778 and 102 918;
                                               * Signature validation process ETSI TS 102 853.

Improvements in packaging and core functionalities:

                                               * CAdES optimisation, CAdES multiple Signer Information. A CAdES PlugTest is occurring in June and July 2015. Changes resulting from this PlugTest will be included in this release. CAdES countersignature will not be supported.
                                               * Impacts from XAdES PlugTest of October 2015.
                                               * Processing of large files.
                                               * Further refactoring of demo applet (size, validation policy editor).
                                               * SOAP and REST Web Services.
                                               * Standalone demo application.

|===
_pass:[*] October 2015: Implementing Acts Art. 27 & 37 (eSig formats)_

=== Version upgrade

To upgrade version of DSS, locate to the `pom.xml` file of your project, search for the properties and then change the dss version in the corresponding field(s).

The following example shows how to switch to DSS version 5.10 using <<BomModule>>.
[source,xml]
.pom.xml
----
<properties>
    ...
    <dss.version>5.10</dss.version>
    ...
</properties>

...

 <dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>eu.europa.ec.joinup.sd-dss</groupId>
            <artifactId>dss-bom</artifactId>
            <version>${dss.version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
----

[[MigrationGuide]]
=== Migration guide

This chapter covers the most significant changes in DSS code occurred between different versions, requiring review and possible changes from code implementors.

For changes within XML Signature Policy please refer <<ValidationPolicyChanges>>.

[cols="2,5,5"]
.Code changes from version 5.11 to 5.12
|===
|Title                               |v5.11                            |v5.12
|Diagnostic Data: ByteRange     a|[source,xml]
----
<SignatureByteRange>0 * * *</SignatureByteRange>
----
                                                                     a|[source,xml]
----
<SignatureByteRange valid="true">0 * * *</SignatureByteRange>
----

|Diagnostic Data: PDFSignatureDictionary     a|[source,xml]
----
<PDFSignatureDictionary>
...
</PDFSignatureDictionary>
----
                                                                     a|[source,xml]
----
<PDFSignatureDictionary consistent="true">
...
</PDFSignatureDictionary>
----

|PDFSignatureService #digest     a|[source,java]
----
PDFSignatureService pdfSignatureService = ...
byte[] digest = pdfSignatureService.digest(toSignDocument, parameters);
----
                                                                     a|[source,java]
----
PDFSignatureService pdfSignatureService = ...
MessageDigest messageDigest = pdfSignatureService.messageDigest(toSignDocument, parameters);
byte[] digest = messageDigest.getValue();
----

|PDFSignatureService: permission dictionary alert     a|[source,java]
----
PDFSignatureService pdfSignatureService = ...
pdfSignatureService.setAlertOnForbiddenSignatureCreation(new ExceptionOnStatusAlert);
----
                                                                     a|[source,java]
----
PAdESService padesService = ...

IPdfObjFactory pdfObjectFactory = new ServiceLoaderPdfObjFactory();
PdfPermissionsChecker pdfPermissionsChecker = new PdfPermissionsChecker();
pdfPermissionsChecker.setAlertOnForbiddenSignatureCreation(new ProtectedDocumentExceptionOnStatusAlert());
pdfObjectFactory.setPdfPermissionsChecker(pdfPermissionsChecker);

service.setPdfObjFactory(pdfObjectFactory);
----

|PDFSignatureService: signature field position alert     a|[source,java]
----
PDFSignatureService pdfSignatureService = ...
pdfSignatureService.setAlertOnSignatureFieldOutsidePageDimensions(new ExceptionOnStatusAlert);
pdfSignatureService.setAlertOnSignatureFieldOverlap(new ExceptionOnStatusAlert);
----
                                                                     a|[source,java]
----
PAdESService padesService = ...

IPdfObjFactory pdfObjectFactory = new ServiceLoaderPdfObjFactory();
PdfSignatureFieldPositionChecker pdfSignatureFieldPositionChecker = new PdfSignatureFieldPositionChecker();
pdfSignatureFieldPositionChecker.setAlertOnSignatureFieldOutsidePageDimensions(new ExceptionOnStatusAlert());
pdfSignatureFieldPositionChecker.setAlertOnSignatureFieldOverlap(new ExceptionOnStatusAlert());
pdfObjectFactory.setPdfSignatureFieldPositionChecker(pdfSignatureFieldPositionChecker);

service.setPdfObjFactory(pdfObjectFactory);
----

|PdfDocumentReader #checkDocumentPermissions     a|[source,java]
----
PdfDocumentReader reader = ...
reader.checkDocumentPermissions();
----
                                                                     a|[source,java]
----
PdfDocumentReader reader = ...
SignatureFieldParameters signatureFieldParameters = ...
PdfPermissionsChecker pdfPermissionsChecker = new PdfPermissionsChecker();
pdfPermissionsChecker.checkDocumentPermissions(reader, signatureFieldParameters);
----

|MimeType namespace     a|[source,java]
----
import eu.europa.esig.dss.model.MimeType;
----
                                                                     a|[source,java]
----
import eu.europa.esig.dss.enumerations.MimeType;
----

|MimeType enumerations     a|[source,java]
----
import eu.europa.esig.dss.model.MimeType;

MimeType.PDF;
----
                                                                     a|[source,java]
----
import eu.europa.esig.dss.enumerations.MimeTypeEnum;

MimeTypeEnum.PDF;
----

|Password protection variable (replaced to `char[]` across modules)     a|[source,java]
----
UserCredentials userCredentials = new UserCredentials("username", "password");
----
                                                                     a|[source,java]
----
UserCredentials userCredentials = new UserCredentials("username", new char[] { 'p', 'a', 's', 's', 'w', 'o', 'r', 'd' });
----

|NativeHTTPDataLoader configuration     a|[source,java]
----
NativeHTTPDataLoader dataLoader = new NativeHTTPDataLoader();
dataLoader.setTimeout(1000);
----
                                                                     a|[source,java]
----
NativeHTTPDataLoader dataLoader = new NativeHTTPDataLoader();
dataLoader.setConnectTimeout(1000);
dataLoader.setReadTimeout(1000);
----

|===

[cols="2,5,5"]
.Code changes from version 5.10/5.10.1 to 5.11
|===
|Title                               |v5.10                            |v5.11
|ASiC container: set signature name     a|[source,java]
----
ASiCWithXAdESSignatureParameters signatureParameters = new ASiCWithXAdESSignatureParameters();
...
signatureParameters.aSiC().setSignatureFileName("signaturesAAA.xml");
----
                                                                     a|[source,java]
----
SimpleASiCWithCAdESFilenameFactory asicFilenameFactory = new SimpleASiCWithCAdESFilenameFactory();
asicFilenameFactory.setSignatureFilename("signaturesAAA.xml");
ASiCWithXAdESService/ASiCWithCAdESService.setAsicFilenameFactory(asicFilenameFactory);
----
_See <<asicFilenameFactory>> for more details._


|Font subset configuration in PDF     a|[source,java]
----
NativePdfBoxVisibleSignatureDrawer nativePdfBoxDrawer = new NativePdfBoxVisibleSignatureDrawer();
nativePdfBoxDrawer.setEmbedFontSubset(true);
...
----
                                                                     a|[source,java]
----
DSSFileFont font = // create font
font.setEmbedFontSubset(true);
...
SignatureImageTextParameters textParameters = new SignatureImageTextParameters();
textParameters.setFont(font);
----

|RevocationDataLoadingStrategy     a|[source,java]
----
CertificateVerifier cv = new CommonCertificateVerifier();
cv.setRevocationDataLoadingStrategy(new OCSPFirstRevocationDataLoadingStrategy());
...
----
                                                                     a|[source,java]
----
CertificateVerifier cv = new CommonCertificateVerifier();
cv.setRevocationDataLoadingStrategyFactory(new OCSPFirstRevocationDataLoadingStrategyFactory());
...
----

|Accepted DigestAlgorithms for OnlineOCSPSource

NOTE: list changed from excluding to including

a|[source,java]
----
OnlineOCSPSource ocspSource = new OnlineOCSPSource();
ocspSource.setDigestAlgorithmsForExclusion(Arrays.asList(DigestAlgorithm.SHA1));

CertificateVerifier cv = new CommonCertificateVerifier();
cv.setOcspSource(ocspSource);
----
                                                                     a|[source,java]
----
RevocationDataVerifier revocationDataVerifier = RevocationDataVerifier.createDefaultRevocationDataVerifier();

List<DigestAlgorithm> digestAlgorithmList = Arrays.asList(DigestAlgorithm.values());
digestAlgorithmList.remove(DigestAlgorithm.SHA1);

revocationDataVerifier.setAcceptableDigestAlgorithms(digestAlgorithmList);

CertificateVerifier cv = new CommonCertificateVerifier();
cv.setRevocationDataVerifier(revocationDataVerifier);
----

|Disable visual comparison

a|[source,java]
----
AbstractPDFSignatureService pdfSignatureService = ...
pdfSignatureService.setMaximalPagesAmountForVisualComparison(0);
...
class MockPdfObjFactory extends PdfBoxNativeObjectFactory {
        @Override
        public PDFSignatureService newPAdESSignatureService() {
            return pdfSignatureService;
        }
...
}
PDFDocumentValidator validator = ...
validator.setPdfObjFactory(new MockPdfObjFactory());
----
                                                                     a|[source,java]
----
IPdfObjFactory pdfObjFactory = new ServiceLoaderPdfObjFactory();
DefaultPdfDifferencesFinder pdfDifferencesFinder = new DefaultPdfDifferencesFinder();
pdfDifferencesFinder.setMaximalPagesAmountForVisualComparison(0);
pdfObjFactory.setPdfDifferencesFinder(pdfDifferencesFinder);
PDFDocumentValidator validator = ...
validator.setPdfObjFactory(pdfObjFactory);
----

|===

[cols="2,5,5"]
.Code changes from version 5.9 to 5.10
|===
|Title                               |v5.9                            |v5.10
|ASiC container extraction     a|[source,java]
----
ASiCExtractResult extractedResult = asicContainerExtractor.extract();
----
                                                                     a|[source,java]
----
ASiCContent extractedResult = asicContainerExtractor.extract();
----

|HttpClient5 transition     a|[source,java]
----
import org.apache.http.*
----
                                                                     a|[source,java]
----
import org.apache.hc.client5.http.*
import org.apache.hc.core5.http.*
----

|FileCacheDataLoader     a|[source,java]
----
fileCacheDataLoader.setCacheExpirationTime(Long.MAX_VALUE);
----
                                                                     a|[source,java]
----
fileCacheDataLoader.setCacheExpirationTime(-1); // negative value means cache never expires
----

|DiagnosticData: PDF signature field name
a|[source,java]
----
List<String> fieldNames = xmlPDFRevision.getSignatureFieldName();
String name = fieldNames.get(i);
----
                                                            a|[source,java]
----
List<PDFSignatureField> signatureFields = xmlPDFRevision.getPDFSignatureField();
String name = signatureFields.get(i).getName();
----

|===

[cols="2,5,5"]
.Code changes from version 5.8 to 5.9
|===
|Title                      |v5.8                            |v5.9
|AIA data loader           a|[source,java]
----
certificateVerifier.setDataLoader(dataLoader);
----
                                                            a|[source,java]
----
AIASource aiaSource = new DefaultAIASource(dataLoader);
certificateVerifier.setAIASource(aiaSource);
----

|Signature Policy Provider           a|[source,java]
----
certificateVerifier.setDataLoader(dataLoader);
----
                                                            a|[source,java]
----
SignaturePolicyProvider signaturePolicyProvider = new SignaturePolicyProvider();
signaturePolicyProvider.setDataLoader(dataLoader);
documentValidator.setSignaturePolicyProvider(signaturePolicyProvider);
----

|JDBC dataSource
a|[source,java]
----
JdbcRevocationSource.setDataSource(dataSource);
----
                                                            a|[source,java]
----
JdbcCacheConnector jdbcCacheConnector = new JdbcCacheConnector(dataSource);
jdbcRevocationSource.setJdbcCacheConnector(jdbcCacheConnector);
----

|DiagnosticData: Signature policy
a|[source,java]
----
String notice = xmlPolicy.getNotice();
Boolean zeroHash = xmlPolicy.isZeroHash();
XmlDigestAlgoAndValue digestAlgoAndValue = xmlPolicy.getDigestAlgoAndValue();
Boolean status = xmlPolicy.isStatus();
Boolean digestAlgorithsEqual = xmlPolicy.isDigestAlgorithsEqual();
----
                                                            a|[source,java]
----
XmlUserNotice notice = xmlPolicy.getUserNotice();
Boolean zeroHash = xmlPolicy.getDigestAlgoAndValue().isZeroHash();
XmlPolicyDigestAlgoAndValue digestAlgoAndValue = xmlPolicy.getDigestAlgoAndValue();
Boolean status = xmlPolicy.getDigestAlgoAndValue().isMatch();
Boolean digestAlgorithsEqual = xmlPolicy.getDigestAlgoAndValue().isDigestAlgorithsEqual();
----

|DiagnosticData: QCStatements
a|[source,java]
----
XmlPSD2Info psd2Info = xmlCertificate.getPSD2Info();
List<XmlOID> qcStatementIds = xmlCertificate.getQCStatementIds();
List<XmlOID> qcTypes = xmlCertificate.getQCTypes();
QCLimitValue qcLimitValue = xmlCertificate.getQCLimitValue();
OID semanticsIdentifier = xmlCertificate.getSemanticsIdentifier();
----
                                                            a|[source,java]
----
XmlPSD2Info psd2Info = xmlCertificate.getQcStatements().getPSD2Info();
QcCompliance qcCompliance = xmlCertificate.getQcStatements().getQcCompliance();
BigInteger qcEuRetentionPeriod = xmlCertificate.getQcStatements().getQcEuRetentionPeriod();
QcEuPDS qcEuPDS = xmlCertificate.getQcStatements().getQcEuPDS();
List<XmlOID> qcTypes = xmlCertificate.getQcStatements().getQCTypes();
QcEuLimitValue qcLimitValue = xmlCertificate.getQcStatements().getQcEuLimitValue();
QCLimitValue qcLimitValue = xmlCertificate.getQcStatements().getQCLimitValue();
OID semanticsIdentifier = xmlCertificate.getQcStatements().getSemanticsIdentifier();
----

|===

[[ValidationPolicyChanges]]
=== Validation policy migration guide

This chapter covers the changes occurred between different versions of DSS within <<validationPolicy>>.

[cols="2,5,5"]
.Policy changes from version 5.11 to 5.12
|===
|Title                                |v5.11                           |v5.12
|ByteRange consistency check          |
----
not present
----
                                                            a|[source,xml]
----
<BasicSignatureConstraints>
    ...
    <ByteRange Level="FAIL" />
    ...
</BasicSignatureConstraints>
----
|PdfSignatureDictionary consistency check          |
----
not present
----
                                                            a|[source,xml]
----
<BasicSignatureConstraints>
...
<PdfSignatureDictionary Level="FAIL" />
...
</BasicSignatureConstraints>
----
|PDF/A checks (see <<PdfaConstraints>>)          |
----
not present
----
                                                            a|[source,xml]
----
<PDFAConstraints>
    <AcceptablePDFAProfiles Level="WARN">
        <Id>PDF/A-2A</Id>
        <Id>PDF/A-2B</Id>
        <Id>PDF/A-2U</Id>
    </AcceptablePDFAProfiles>
    <PDFACompliant Level="WARN" />
</PDFAConstraints>
----

|===

[cols="2,5,5"]
.Policy changes from version 5.10 to 5.11
|===
|Title                                |v5.10                           |v5.11
|JWA Elliptic Curve Key Size (see RFC 7518)          |
----
not present
----
                                                            a|[source,xml]
----
<SignedAttributes>
    ...
    <EllipticCurveKeySize Level="WARN" />
    ...
</SignedAttributes>
----

|===

.Policy changes from version 5.9 to 5.10
|===
|Title                                |v5.9                            |v5.10
|Revocation freshness +
(time constraint enforced)           a|[source,xml]
----
<CertificateConstraints>
    ...
    <RevocationDataFreshness Level="FAIL" />
    ...
</CertificateConstraints>

...

<RevocationConstraints>
    ...
	<RevocationFreshness Level="FAIL" Unit="DAYS" Value="0" />
    ...
</RevocationConstraints>
----
                                                            a|[source,xml]
----
<CertificateConstraints>
    ...
    <RevocationFreshness Level="FAIL" Unit="DAYS" Value="0" />
    ...
</CertificateConstraints>
----

|Revocation freshness +
(no time constraint)           a|[source,xml]
----
<CertificateConstraints>
    ...
    <RevocationDataFreshness Level="FAIL" />
    ...
</CertificateConstraints>

...

<RevocationConstraints>
    ...
	<!--<RevocationFreshness />-->
    ...
</RevocationConstraints>
----
                                                            a|[source,xml]
----
<CertificateConstraints>
    ...
    <RevocationFreshnessNextUpdate Level="FAIL" />
    ...
</CertificateConstraints>
----

|Signing-certificate reference certificate chain           a|[source,xml]
----
<CertificateConstraints>
    ...
    <SemanticsIdentifierForNaturalPerson />
    <SemanticsIdentifierForLegalPerson />
    ...
</CertificateConstraints>
----
                                                            a|[source,xml]
----
<CertificateConstraints>
    ...
    <SemanticsIdentifier>
        <Id>0.4.0.194121.1.1</Id> // for natural person
        <Id>0.4.0.194121.1.2</Id> // for legal person
    </SemanticsIdentifier>
    ...
</CertificateConstraints>
----

|===

[cols="2,5,5"]
.Policy changes from version 5.8 to 5.9
|===
|Title                      |v5.8                            |v5.9
|Revocation nextUpdate check           a|[source,xml]
----
<CertificateConstraints>
    ...
    <RevocationDataNextUpdatePresent />
    ...
</CertificateConstraints>
----
                                                            a|[source,xml]
----
<CertificateConstraints>
    ...
    <CRLNextUpdatePresent />
    <OCSPNextUpdatePresent />
    ...
</CertificateConstraints>
----

|Signing-certificate reference certificate chain           a|[source,xml]
----
<SignedAttributesConstraints>
    ...
    <AllCertDigestsMatch />
    ...
</SignedAttributesConstraints>
----
                                                            a|[source,xml]
----
<SignedAttributesConstraints>
    ...
    <SigningCertificateRefersCertificateChain />
    ...
</SignedAttributesConstraints>
----

|===

=== Frequently asked questions and implementation issues

This chapter covers the most frequently asked questions and issues occurring in implementations using DSS.

[cols="2,3,7"]
.Possible problems and solutions
|===
|Version                    |Description                                   |Solution

|v5.12                      |Performance downgrade on TLValidationJob/certificates loading       a|Starting from version 1.71 cryptographic library BouncyCastle enforces a secure validation of imported RSA keys. In order to get back to the original behavior (secure validation skipped), the following system property should be added before executing methods requiring certificate creation (such as TLValidationJob):

[source,java]
----
System.setProperty("org.bouncycastle.rsa.max_mr_tests", "0");
----

The property is available since BouncyCastle 1.73.

|v5.9 and higher            |Returned signature level is *_NOT_ETSI       a|*DSS 5.9* enforces validation of AdES BASELINE signature profiles as per ETSI standards. *The signature is not BASELINE* if you receive _*_NOT_ETSI_ output. +
                                                                            *Since DSS 5.10 a support of AdES extended signature profiles* for (XAdES and CAdES) has been added as per ETSI standards.

|v5.8 and higher            |PAdES : performance downgrade                a|DSS has introduced additional PDF validation functionality aiming to detect malisious modifications occurred after signature creation. These validation operations are expensive and may impact the total execution time. In case the recognition of such attacks is not required, it may be disabled by configuring the relevant objects (see <<DisablingPdfComparison>> for an example). For more information about the modification detection classes please see <<ShadowAttackDetection>> and <<ObjectModificationDetection>>.

|v5.7 and higher            |How to filter certain Trusted Lists (for example countries)                a|To filter LOTLs or TLs you can use <<LotlTlPredicates>>. For example, to filter TLs from Germany and Romania:

[source,java]
----
include::{sourcetestdir}/eu/europa/esig/dss/cookbook/example/snippets/TLValidationJobSnippets.java[tags=predicate-country]
----

|v5.2 and higher            |XAdES : performance downgrade                a|Xalan dependency has been removed as http://www.odi.ch/weblog/posting.php?posting=689[deprecated]. +
                                                                            We do not recommend to use Xalan in production.
                                                                            To use Xalan, you will need to remove security attributes:
[source,java]
----
XmlDefinerUtils.getInstance().setTransformerFactoryBuilder(
TransformerFactoryBuilder.getSecureTransformerBuilder()
.removeAttribute(XMLConstants.ACCESS_EXTERNAL_DTD)
.removeAttribute(XMLConstants.ACCESS_EXTERNAL_STYLESHEET));
----

|v5.2 and higher            |Error: "SECURITY : unable to set attribute ..."             a|The error is more likely caused by a use of deprecated Xalan or Xerces dependency. Please see the previous answer for resolution.

|all versions              a|Maven build fails       a| Please verify whether you need to build DSS. See <<HowToStart>> for more details about DSS integration. If you need to build DSS, please use one of the quick profiles (see <<MavenBuildProfiles>> for more information).

|all versions              a|Build fails when using `quick` profile       a| * DSS 5.9 and lower: +
                                                                             Build the following modules using `mvn clean install` (without any profile):
                                                                             ** `dss-utils`;
                                                                             ** `dss-crl-parser`;
                                                                             ** `dss-test`;
                                                                             ** `dss-pades`;
                                                                             ** `dss-asic-common` _(since DSS 5.8)._
                                                                             * DSS 5.10 and after:
                                                                             Use `quick-init` profile for the first build of DSS.

|all versions              a|Unable to access DSS Maven repository       a|If the error occurs, more likely DSS-team is already aware about the issue. +
                                                                           You need to try to connect again in a few hours.

|all versions              a|DSS produces invalid signature       a|Please verify that you provide *the same signature parameter values* within methods _#getDataToSign_ and _#signDocument_. Specifically please pay attention to the `Date` provided within `parameters.bLevel().setSigningDate(date)` method (shall be the same). For more information please see <<SignatureCreationInDSS>>.

|all versions              a|When validating a signature I receive `INDETERMINATE/NO_CERTIFICATE_CHAIN_FOUND` indication       a|The result means the validator was not able to reach a trust anchor when validating the certificate chain of the signature. More likely the issue is caused by the fact you have *not configured a trusted certificate source* within the used `CertificateVerifier`. To do it, you need to add trust anchors to the instance of CertificateVerifier you use within DocumentValidator:

[source,java,indent=0]
.Trusted certificate source configuration
----
include::{sourcetestdir}/eu/europa/esig/dss/cookbook/example/validate/XAdES132OnlyTest.java[tags=trustAnchors]
----

It is also possible to configure trusted certificate source automatically using EU LOTL. See <<tlValidationJob>> for more details.

|all versions              a|Revocation data is missing on LT-level extension       a|Verify whether the trust anchors and CRL/OCSP sources are configured appropriately. You need to provide them to the used CertificateVerifier:

[source,java,indent=0]
.CertificateVerifier configuration
----
include::{sourcetestdir}/eu/europa/esig/dss/cookbook/example/sign/SignXmlXadesLTTest.java[tags=certificate-verifier]
----

|all versions              a|CRL issued before certificate's notBefore is ignored       a|According to RFC 5280 (cf. <<R21>>), a CRL shall contain a complete list of revoked unexpired certificates issued by a CA. Thus, it may not contain not yet issued certificates (i.e. with _notBefore_ date after the CRL's _thisUpdate_). Therefore such CRLs cannot be considered as a relevant source of revocation information for the corresponding certificate during the validation process. To resolve the issue, please use an OCSP response, if feaseble, or wait for a CRL update.

|all versions              a|I receive error _"Unable to build a certificate chain until a trusted list"_ while signature is validated as `TOTAL_PASSED`     a|During the validation DSS performs two processes: AdES validation as per ETSI EN 319 102-1 (cf. <<R09>>) and qualification determination as per ETSI TS 119 615 (cf. <<R14>>). While `TOTAL_PASSED` indication is a final result of AdES validation process, the aforementioned error message is returned by a signature qualification determination process, meaning the corresponding Trusted List has not reached the trust anchor for the certificate chain. Please note, that the qualification can be determined only for signatures with trusted certificates coming from a Trusted List. To configure a trusted certificate source using a EU LOTL or an alternative Trusted List, please see <<tlValidationJob>> chapter for more details.

|all versions              a|Error "Document format not recognized/handled"     a|DSS loads the relevant `DocumentValidator` using a `ServiceLoader` searching accross all available implementations. Please ensure the corresponding module supporting validation of particular signature module has been added to a list of dependencies within `pom.xml` file of your project (e.g. `dss-xades` for XML/XAdES signatures). For more information about available modules please see <<CoreModules>> section.

|all versions              a|`NO_CERTIFICATE_CHAIN_FOUND` is returned on LOTL validation     a|Please ensure a trusted keystore provided to the validation has been configured with end-entity certificates defined in the https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=uriserv:OJ.C_.2019.276.01.0001.01.ENG[Official Journal of the European Commission (OJEU)]. A pre-configured EU OJ keystore you may find within dss-demonstrations https://github.com/esig/dss-demonstrations/blob/master/dss-demo-webapp/src/main/resources/keystore.p12[repository] with a password defined in https://github.com/esig/dss-demonstrations/blob/master/dss-demo-webapp/src/main/resources/dss.properties[properties] file. For more information please see <<CompleteConfigurationOfEuLOTL>>.

|all versions              a|DSS successfully validates an expired timestamp created with a trusted certificate     a|DSS performs validation according to ETSI EN 319 102-1 standard (cf. <<R13>>). According to the algorithm, the validation of certificate chain stops when reaching a trust anchor provided as an input to the validation process. Thus, the AdES validation process automatically results to a valid "X.509 certificate" building block for signatures or timestamps created with a trusted end-entity certificate. If you extract a trusted certificate source from a LOTL/TL, then you may try to filter extracted certificates using <<LotlTlPredicates>>.

|all versions              a|I have a problem when signing using Nexu. Can you help me?     a|While the community version of Nexu is used within _dss-demonstrations_ web-application, Nexu is not part of DSS package, therefore DSS support does not extend to the Nexu project. We do  our best to help users in case of any issues, but DSS does not have liability whatsoever over open-source version of Nexu.

|all versions              a|Does DSS provide a qualified signature validation service?       a|No, DSS is not a qualified signature validation service. However, DSS provides a possibility to create one based on its core code by configuring <<validationPolicy>> and other corresponding constraints. Please also note that https://ec.europa.eu/digital-building-blocks/DSS/webapp-demo/home[DSS Demonstration Webapp] merely provides a live demonstration of available functionalities within DSS framework, but not an end-to-end signature creation or validation tool.

|all versions              a|Parallel signature breaks existing enveloped XAdES signature     a|If the existing XAdES signature contains _"http://www.w3.org/2000/09/xmldsig#enveloped-signature"_ transform, then the parallel signing is not allowed. To be able to create parallel enveloped signatures, you should use another transform such as XPath or XPath Filter 2.0 transform. By default, DSS already uses XPath Transform 2.0 for enveloped signatures, thus allowing parallel signing.

|all versions              a|When I move enveloped XAdES signature to another XML (e.g. to a SOAP envelope), it becomes invalid       a|Enveloped XAdES signature covers the whole content of a parent XML document. Therefore, a change of the signature's envelope may result to a signature invalidity. To avoid it, create signature within the target XML document or use another signature packaging (e.g. enveloping).

|all versions              a|XAdES signature became invalid after pretty-printing while I use canonicalization       a|Canonicalization does not normalize whitespace and new line characters occurring between XML nodes. Therefore pretty-printing should be avoided after signature creation. To create a pretty-printed signature with DSS, you may use the following signature parameter:

[source,java,indent=0]
----
include::{sourcetestdir}/eu/europa/esig/dss/cookbook/example/sign/SignXmlXadesBPropertiesTest.java[tags=prettyPrint]
----

|all versions              a|PAdES validation without sending the document       a|PAdES format *requires a complete document* to perform a signature validation. You cannot validate a PDF signature as a DETACHED XAdES or CAdES. +
                                                                                   The only possible way to perform the *cryptographic signature validation* is to extract the embedded CMS signature and the covered range as a detached document. However the validation result will not be able to conclude it as a valid PAdES nor CAdES Baseline.

|all versions              a|When validating a PDF with embedded `CAdES-BASELINE` signature the returned format is `PDF_NOT_ETSI`       a|`PAdES-BASELINE` format establishes some limitations on the embedded CMS signature, which are not compliant with `CAdES-BASELINE` signatures. Therefore, *it is not possible* to have a valid `PAdES-BASELINE` profile with embedded `CAdES-BASELINE` signature. For more information about supported CMS please see <<R03>>.

|all versions              a|How to add multiple visual signature fields on PDF signing?       a|This functionality is not supported by DSS. Adding multiple signature fields associated with a signle signature value contradicts ISO 32000-1 and therefore not recomended for interoperability reasons. The only valid choice is to sign a document multiple times.

|all versions              a|DSS returns `SIG_CRYPTO_FAILURE` for a PDF signature while Adobe validates the signature succesfully       a|DSS performs a PDF signature validation according to ETSI EN 319 142-1 (cf. <<R03>>) and ISO 32000-1 (cf. <<R06>>), enforcing the defined rules, while other PDF-readers may ease some requirements concerning the structure of a PDF document or a CMS signature. Please verify our https://ec.europa.eu/digital-building-blocks/tracker/projects/DSS/issues[Jira] for similar issues or create a new one to request a document verification unless you do not find a similar case.

|all versions              a|DSS successfully validates a PDF signature, while another PDF reader complains that the document's content has been modified.       a|Validation of document modifications is not standardized, therefore the produced results may differ between different validation tools. DSS does it best to detect malisious modifications occurred after signature revision (see <<ShadowAttackDetection>> and <<ObjectModificationDetection>> for more detail). Regardless of the obtained result, an error or a warning received after visual document content comparison should only be considered as a hint, and it is always recommended to manually verify the differencies between signed and final document revisions in order to decide whether the change is acceptable or not.

|all versions              a|DSS breaks PDF/A conformance on a signature creation       a|DSS does not claim compliance of produced documents to a PDF/A format. The goal of DSS is to ensure conformance to AdES signature format for created signatures. We do our best to keep conformity of PDF/A documents after signing, but we do not take any liability on this matter.

|all versions              a|A signature-time-stamp embedded within CMS of the second PDF signature does not provide a POE for the first PDF signature      a|DSS recognizes timestamps as per ETSI EN 319 142-1 (cf. <<R03>>). The standard defines the following timestamps to be related to a signature: a signature-time-stamp embedded within signature's CMS Signed Data and a document timestamp covering the signature in its ByteRange explicitly. All other POE or timestamps covering a signature in indirect way are not considered as a POE during the AdES signature validation process.

|all versions              a|I have a question not covered above      a|Feel free to reach us using https://ec.europa.eu/digital-building-blocks/tracker/projects/DSS/issues[JIRA issues tracker].

|===



