:sectnums:
:sectnumlevels: 5
:sourcetestdir: ../../../test/java
:samplesdir: ../_samples
:imagesdir: images/

== eIDAS
=== Verifying the type and qualified status of a certificate.

==== Type of a certificate
A certificate can be for electronic signature, for electronic seal or for website authentication.

Below is an example of the verification of the type of a certificate:

!!! TODO: create CertificateTypeTest.java !!!
[source,java,indent=0]
.Determination of the type of certificate
----
include::{sourcetestdir}/eu/europa/esig/dss/cookbook/example/validate/CertificateTypeTest.java[tags=demo]
----

==== Qualified status of a certificate

Explanations as well as an example on the determination of the qualified status of a certificate are presented in section <<CertificateValidation>>.

===== Qualified certificate for WebSite Authentication (QWAC)

With DSS, it is possible to validate SSL certificate against the EUMS TL and the ETSI TS 119 615 to determine if it is a Qualified certificate for WebSite Authentication (QWAC).

[source,java,indent=0]
.Validate an SSL certificate and retrieve its qualification level
----
include::{sourcetestdir}/eu/europa/esig/dss/cookbook/example/validate/QWACValidationTest.java[tags=demo]
----




=== Verifying the type (eSig, eSeal) and qualified status of an AdES signature.
==== Type of an AdES
Under eIDAS, there exist advanced electronic signatures and seals.

Below is an example of the verification of the type:

!!! TODO: create AdESTypeTest.java !!!

[source,java,indent=0]
.Determination of the type of an AdES
----
include::{sourcetestdir}/eu/europa/esig/dss/cookbook/example/validate/AdESTypeTest.java[tags=demo]
----



==== Qualified status of an AdES signature
Below is an example of the validation and verification of the qualified status of an AdES signature:

!!! TODO: create AdESTypeTest.java !!!

[source,java,indent=0]
.Validate an AdES signature and retrieve its qualification level
----
include::{sourcetestdir}/eu/europa/esig/dss/cookbook/example/validate/AdESValidationTest.java[tags=demo]
----

=== Verifying the qualified status of a timestamp

DSS is able to determine a qualification level of a timestamp, if a relative information about TrustServiceProviders is provided to a certificate verifier (loaded automatically to a trusted certificate source with <<tlValidationJob>>) (cf. <<R14>>).

Three qualification levels are supported by DSS and can be obtained :

* `QTSA` (issued from a granted trust service with TSA/QTST type at the timestamp production time);
* `TSA` any other from a known trust anchor;
* `N/A` for others.

The following example verifies the qualification level of a timestamp

!!! TODO: create TimestampValidationTest.java !!!

[source,java,indent=0]
.Validate an timestamp and retrieve its qualification level
----
include::{sourcetestdir}/eu/europa/esig/dss/cookbook/example/validate/TimestampValidationTest.java[tags=demo]
----