:sectnums:
:sectnumlevels: 5
:sourcetestdir: ../../../test/java
:samplesdir: ../_samples
:imagesdir: ../images/

[[ValidationPolicyChanges]]
=== Validation policy migration guide

This chapter covers the changes occurred between different versions of DSS within <<validationPolicy>>.

[cols="2,5,5"]
.Policy changes from version 6.2 to 6.3
|===
|Title                                |v6.2                           |v6.3
|XML Trusted List structure validation                          |
----
Not present
----
a|[source,xml]
----
<eIDAS>
    ...
    <TLStructure Level="WARN" />
    ...
</eIDAS>
----

|===

[cols="2,5,5"]
.Policy changes from version 6.1 to 6.2
|===
|Title                                |v6.1                           |v6.2
|NoRevAvail certificate extension     |
----
Not present
----
                                                                     a|[source,xml]
----
<SignatureConstraints>
    ...
    <BasicSignatureConstraints>
        ...
        <SigningCertificate>
            ...
            <RevocationDataSkip Level="INFORM">
                <CertificateExtensions>
                    ...
                    <Id>2.5.29.56</Id> <!-- noRevAvail -->
                </CertificateExtensions>
            </RevocationDataSkip>
            ...
            <NoRevAvail Level="WARN" />
            ...
        </SigningCertificate>
        <CACertificate>
            ...
            <ForbiddenExtensions Level="FAIL">
                ...
                <Id>2.5.29.56</Id> <!-- noRevAvail -->
            </ForbiddenExtensions>
            ...
        </CACertificate>
    </BasicSignatureConstraints>
    ...
</SignatureConstraints>
----

|ASiC timestamp and evidence record consequent coverage     |
----
Not present
----
                                                                     a|[source,xml]
----
<Timestamp>
    ...
	<ContainerSignedAndTimestampedFilesCovered Level="FAIL" />
    ...
</Timestamp>
...
<EvidenceRecord>
    ...
    <ContainerSignedAndTimestampedFilesCovered Level="WARN" />
    ...
</EvidenceRecord>
----

|Detached evidence record signed data coverage     |
----
Not present
----
                                                                     a|[source,xml]
----
<EvidenceRecord>
    ...
    <SignedFilesCovered Level="WARN" />
    ...
</EvidenceRecord>
----

|TL Version     a|[source,xml]
----
<eIDAS>
    ...
    <TLVersion Level="FAIL" value="5" />
    ...
</eIDAS>
----
                                                                     a|[source,xml]
----
<eIDAS>
    ...
    <TLVersion Level="FAIL">
        <Id>5</Id>
        <Id>6</Id>
    </TLVersion>
    ...
</eIDAS>
----

|CAdES archive-time-stamp-v3 ats-hash-index validation     |
----
Not present
----
                                                                     a|[source,xml]
----
<Timestamp>
    ...
    <AtsHashIndex Level="WARN" />
    ...
</Timestamp>
----

|Cryptographic constraint minimum key sizes                          a|[source,xml]
----
<MiniPublicKeySize>
    <Algo Size="1024">DSA</Algo>
    <Algo Size="1024">RSA</Algo>
    <Algo Size="1024">RSASSA-PSS</Algo>
    <Algo Size="160">ECDSA</Algo>
    <Algo Size="160">PLAIN-ECDSA</Algo>
</MiniPublicKeySize>
----
                                                                     a|[source,xml]
----
<MiniPublicKeySize>
    <Algo Size="1024">DSA</Algo>
    <Algo Size="786">RSA</Algo>
    <Algo Size="786">RSASSA-PSS</Algo>
    <Algo Size="160">ECDSA</Algo>
    <Algo Size="160">PLAIN-ECDSA</Algo>
</MiniPublicKeySize>
----

|Cryptographic constraint expiration dates.

NOTE: Limited number of algorithms is listed in the example.
Please see more at <<defaultXmlPolicy>>.                             a|[source,xml]
----
<AlgoExpirationDate Level="FAIL" Format="yyyy" UpdateDate="2022" LevelAfterUpdate="WARN">
    <Algo Date="2009">SHA1</Algo>
    <Algo Date="2026">SHA224</Algo>
    <Algo Date="2029">SHA256</Algo>
    <Algo Date="2029">SHA384</Algo>
    <Algo Date="2029">SHA512</Algo>
    <Algo Date="2029">SHA3-256</Algo>
    <Algo Date="2029">SHA3-384</Algo>
    <Algo Date="2029">SHA3-512</Algo>
    <Algo Date="2009" Size="1024">RSA</Algo>
    <Algo Date="2016" Size="1536">RSA</Algo>
    <Algo Date="2026" Size="1900">RSA</Algo>
    <Algo Date="2029" Size="3000">RSA</Algo>
    <Algo Date="2013" Size="160">ECDSA</Algo>
    <Algo Date="2013" Size="192">ECDSA</Algo>
    <Algo Date="2016" Size="224">ECDSA</Algo>
    <Algo Date="2029" Size="256">ECDSA</Algo>
    <Algo Date="2029" Size="384">ECDSA</Algo>
    <Algo Date="2029" Size="512">ECDSA</Algo>
</AlgoExpirationDate>
----
                                                                     a|[source,xml]
----
<AlgoExpirationDate Level="FAIL" Format="yyyy-MM-dd" UpdateDate="2025-01-01" LevelAfterUpdate="WARN">
    <Algo Date="2012-08-01">SHA1</Algo>
    <Algo Date="2029-01-01">SHA224</Algo>
    <Algo>SHA256</Algo> <!-- R -->
    <Algo>SHA384</Algo> <!-- R -->
    <Algo>SHA512</Algo> <!-- R -->
    <Algo>SHA3-256</Algo> <!-- R -->
    <Algo>SHA3-384</Algo> <!-- R -->
    <Algo>SHA3-512</Algo> <!-- R -->
    <Algo Date="2010-08-01" Size="786">RSA</Algo>
    <Algo Date="2019-10-01" Size="1024">RSA</Algo>
    <Algo Date="2019-10-01" Size="1536">RSA</Algo>
    <Algo Date="2029-01-01" Size="1900">RSA</Algo>
    <Algo Date="2029-01-01" Size="3000">RSA</Algo>
    <Algo Size="3000">RSASSA-PSS</Algo> <!-- R -->
    <Algo Date="2012-08-01" Size="160">ECDSA</Algo>
    <Algo Date="2012-08-01" Size="163">ECDSA</Algo>
    <Algo Date="2021-10-01" Size="224">ECDSA</Algo>
    <Algo Size="256">ECDSA</Algo> <!-- R -->
</AlgoExpirationDate>
----

|===

[cols="2,5,5"]
.Policy changes from version 5.13/6.0 to 6.1
|===
|Title                                |v6.0                           |v6.1
|HashTree renewal time-stamp check    |
----
Not present
----
                                                                     a|[source,xml]
----
<EvidenceRecord>
    ...
    <HashTreeRenewal Level="FAIL" />
    ...
</EvidenceRecord>
----

|OCSP-no-check revocation skip    |
----
Not present
----
                                                                     a|[source,xml]
----
<Revocation>
    ...
    <BasicSignatureConstraints>
        ...
        <SigningCertificate>
            ...
            <RevocationDataSkip Level="IGNORE">
                <CertificateExtensions>
                    <Id>1.3.6.1.5.5.7.48.1.5</Id> <!-- ocsp_noCheck -->
                </CertificateExtensions>
            </RevocationDataSkip>
            ...
        </SigningCertificate>
        ...
    </BasicSignatureConstraints>
    ...
</Revocation>
----

|val-assured-ST-certs revocation skip    |
----
Not present
----
                                                                     a|[source,xml]
----
<SignatureConstraints>
    ...
    <BasicSignatureConstraints>
        ...
        <SigningCertificate>
            ...
            <RevocationDataSkip Level="INFORM">
                <CertificateExtensions>
						<Id>0.4.0.194121.2.1</Id> <!-- valassured-ST-certs -->
                </CertificateExtensions>
            </RevocationDataSkip>
            ...
        </SigningCertificate>
        ...
    </BasicSignatureConstraints>
    ...
</SignatureConstraints>
----
_(same for CounterSignatureConstraints)_

|RSASSA-PSS encryption algorithm                                 a|[source,xml]
----
<Cryptographic Level="FAIL">
    ...
    <AcceptableEncryptionAlgo>
        ...
        <Algo>RSA</Algo>
        ...
    </AcceptableEncryptionAlgo>
    <MiniPublicKeySize>
        ...
        <Algo Size="1024">RSA</Algo>
        ...
    </MiniPublicKeySize>
    <AlgoExpirationDate Level="FAIL" Format="yyyy" UpdateDate="2022" LevelAfterUpdate="WARN">
        ...
        <Algo Date="2009" Size="1024">RSA</Algo>
        <Algo Date="2016" Size="1536">RSA</Algo>
        <Algo Date="2026" Size="1900">RSA</Algo>
        <Algo Date="2029" Size="3000">RSA</Algo>
        ...
    </AlgoExpirationDate>
    ...
</Cryptographic>
----
                                                  a|[source,xml]
----
<Cryptographic Level="FAIL">
    ...
    <AcceptableEncryptionAlgo>
        ...
        <Algo>RSA</Algo>
        <Algo>RSASSA-PSS</Algo>
        ...
    </AcceptableEncryptionAlgo>
    <MiniPublicKeySize>
        ...
        <Algo Size="1024">RSA</Algo>
        <Algo Size="1024">RSASSA-PSS</Algo>
        ...
    </MiniPublicKeySize>
    <AlgoExpirationDate Level="FAIL" Format="yyyy" UpdateDate="2022" LevelAfterUpdate="WARN">
        ...
        <Algo Date="2009" Size="1024">RSA</Algo>
        <Algo Date="2016" Size="1536">RSA</Algo
        <Algo Date="2026" Size="1900">RSA</Algo>
        <Algo Date="2029" Size="3000">RSA</Algo>
        <Algo Date="2009" Size="1024">RSASSA-PSS</Algo>
        <Algo Date="2016" Size="1536">RSASSA-PSS</Algo>
        <Algo Date="2026" Size="1900">RSASSA-PSS</Algo>
        <Algo Date="2029" Size="3000">RSASSA-PSS</Algo>
        ...
    </AlgoExpirationDate>
    ...
</Cryptographic>
----

|Original document name validation                 a|
A document with a different name than the reference's URI does not match
                                                   a|[source,xml]
----
<BasicSignatureConstraints>
    ...
    <ReferenceDataNameMatch Level="WARN" />
    ...
</BasicSignatureConstraints>
----

|XML Manifest validation constraints               a|
Aligned with reference data constraints
a|[source,xml]
----
<BasicSignatureConstraints>
    ...
    <ManifestEntryObjectExistence Level="WARN" />
    <ManifestEntryObjectGroup Level="WARN" />
    <ManifestEntryObjectIntact Level="FAIL" />
    <ManifestEntryNameMatch Level="WARN" />
    ...
</BasicSignatureConstraints>
----

|===

[cols="2,5,5"]
.Policy changes from version 5.12 to 5.13
|===
|Title                                |v5.12                           |v5.13
|Trust Service checks                a|[source,xml]
----
<BasicSignatureConstraints>
    ...
    <TrustedServiceTypeIdentifier Level="WARN">
        <Id>http://uri.etsi.org/TrstSvc/Svctype/CA/QC</Id>
    </TrustedServiceTypeIdentifier>
    <TrustedServiceStatus Level="FAIL">
        <Id>http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/undersupervision</Id>
        <Id>http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/accredited</Id>
        <Id>http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/supervisionincessation</Id>
        <Id>http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/granted</Id>
        <Id>http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/withdrawn</Id>
    </TrustedServiceStatus>
    ...
</BasicSignatureConstraints>
----
                                                            a|[source,xml]
----
<BasicSignatureConstraints>
    ...
    <TrustServiceTypeIdentifier Level="WARN">
        <Id>http://uri.etsi.org/TrstSvc/Svctype/CA/QC</Id>
    </TrustServiceTypeIdentifier>
    <TrustServiceStatus Level="FAIL">
        <Id>http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/undersupervision</Id>
        <Id>http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/accredited</Id>
        <Id>http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/supervisionincessation</Id>
        <Id>http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/granted</Id>
        <Id>http://uri.etsi.org/TrstSvc/TrustedList/Svcstatus/withdrawn</Id>
    </TrustServiceStatus>
    ...
</BasicSignatureConstraints>
----

|Issuer DN check                                  |
----
not present
----
                                                  a|[source,xml]
----
<SigningCertificate>
    ...
    <IssuerName Level="FAIL" />
    ...
</SigningCertificate>
----

|Signature Policy                                 a|[source,xml]
----
<SignatureConstraints>
    ...
    <PolicyAvailable Level="FAIL" />
    <PolicyHashMatch Level="FAIL" />
    ...
</SignatureConstraints>
----
                                                  a|[source,xml]
----
<SignatureConstraints>
    ...
    <PolicyAvailable Level="INFORM" />
    <PolicyHashMatch Level="WARN" />
    ...
</SignatureConstraints>
----

|===

[cols="2,5,5"]
.Policy changes from version 5.11 to 5.12
|===
|Title                                |v5.11                           |v5.12
|ByteRange consistency checks         |
----
not present
----
                                                            a|[source,xml]
----
<BasicSignatureConstraints>
    ...
    <ByteRange Level="FAIL" />
    <ByteRangeCollision Level="WARN" />
    <!-- ByteRangeAllDocument Level="WARN" -->
    ...
</BasicSignatureConstraints>
----
|PdfSignatureDictionary consistency check          |
----
not present
----
                                                            a|[source,xml]
----
<BasicSignatureConstraints>
...
<PdfSignatureDictionary Level="FAIL" />
...
</BasicSignatureConstraints>
----
|PDF/A checks (see <<PdfaConstraints>>)          |
----
not present
----
                                                            a|[source,xml]
----
<PDFAConstraints>
    <AcceptablePDFAProfiles Level="WARN">
        <Id>PDF/A-2A</Id>
        <Id>PDF/A-2B</Id>
        <Id>PDF/A-2U</Id>
    </AcceptablePDFAProfiles>
    <PDFACompliant Level="WARN" />
</PDFAConstraints>
----
|Forbidden extensions check                     |
----
not present
----
                                                            a|[source,xml]
----
<SigningCertificate>
    ...
    <ForbiddenExtensions Level="FAIL">
        <Id>1.3.6.1.5.5.7.48.1.5</Id> <!-- ocsp_noCheck -->
    </ForbiddenExtensions>
    ...
</SigningCertificate>
----
|CA certificate BasicConstraints check          |
----
not present
----
                                                            a|[source,xml]
----
<CACertificate>
    ...
    <CA Level="FAIL" />
    <MaxPathLength Level="FAIL" />
    ...
</CACertificate>
----
|KeyUsage for CA certificates                     |
----
not enforced
----
                                                            a|[source,xml]
----
<CACertificate>
    ...
    <KeyUsage Level="FAIL">
        <Id>keyCertSign</Id>
    </KeyUsage>
    ...
</CACertificate>
----
|Extended key usage for timestamp certificates              a|[source,xml]
----
<Timestamp>
    <SigningCertificate>
        ...
        <ExtendedKeyUsage Level="WARN">
            <Id>timeStamping</Id>
        </ExtendedKeyUsage>
        ...
    </SigningCertificate>
</Timestamp>
----
                                                            a|[source,xml]
----
<Timestamp>
    <SigningCertificate>
        ...
        <ExtendedKeyUsage Level="FAIL">
            <Id>timeStamping</Id>
        </ExtendedKeyUsage>
        ...
    </SigningCertificate>
</Timestamp>
----
|Certificate Policy Tree                     |
----
not enforced
----
                                                            a|[source,xml]
----
<SigningCertificate>
    ...
    <PolicyTree Level="WARN" />
    ...
</SigningCertificate>
----
|Name Constraints                     |
----
not enforced
----
                                                            a|[source,xml]
----
<SigningCertificate>
    ...
    <NameConstraints Level="WARN" />
    ...
</SigningCertificate>
----
|Supported Critical Extensions                     |
----
not enforced
----
                                                            a|[source,xml]
----
<SigningCertificate>
    ...
    <SupportedCriticalExtensions Level="WARN">
        <Id>2.5.29.15</Id>
        <Id>2.5.29.32</Id>
        <Id>2.5.29.17</Id>
        <Id>2.5.29.19</Id>
        <Id>2.5.29.30</Id>
        <Id>2.5.29.36</Id>
        <Id>2.5.29.37</Id>
        <Id>2.5.29.31</Id>
        <Id>2.5.29.54</Id>
        <Id>1.3.6.1.5.5.7.1.3</Id>
    </SupportedCriticalExtensions>
    ...
</SigningCertificate>
----
|ResponderId for OCSP response                     |
----
not enforced
----
                                                            a|[source,xml]
----
<Revocation>
    ...
    <OCSPResponderIdMatch Level="FAIL" />
    ...
</Revocation>
----
|Expiration of cryptographic suites              a|[source,xml]
----
<Cryptographic Level="FAIL">
    ...
    <AlgoExpirationDate Format="yyyy">
        <!-- Digest algorithms -->
        <Algo Date="2005">MD5</Algo>
        <Algo Date="2009">SHA1</Algo>
        <Algo Date="2026">SHA224</Algo>
        ...
        <!-- Encryption algorithms -->
        ...
    </AlgoExpirationDate>
    ...
</Cryptographic>
----
                                                            a|[source,xml]
----
<Cryptographic Level="FAIL">
    ...
    <AlgoExpirationDate Level="FAIL" Format="yyyy" UpdateDate="2022" LevelAfterUpdate="WARN">
        <!-- Digest algorithms -->
        <Algo Date="2005">MD5</Algo>
        <Algo Date="2009">SHA1</Algo>
        <Algo Date="2026">SHA224</Algo>
        ...
        <!-- Encryption algorithms -->
        ...
    </AlgoExpirationDate>
    ...
</Cryptographic>
----

|===

[cols="2,5,5"]
.Policy changes from version 5.10 to 5.11
|===
|Title                                |v5.10                           |v5.11
|JWA Elliptic Curve Key Size (see RFC 7518)          |
----
not present
----
                                                            a|[source,xml]
----
<SignedAttributes>
    ...
    <EllipticCurveKeySize Level="WARN" />
    ...
</SignedAttributes>
----

|===

.Policy changes from version 5.9 to 5.10
|===
|Title                                |v5.9                            |v5.10
|Revocation freshness +
(time constraint enforced)           a|[source,xml]
----
<CertificateConstraints>
    ...
    <RevocationDataFreshness Level="FAIL" />
    ...
</CertificateConstraints>

...

<RevocationConstraints>
    ...
	<RevocationFreshness Level="FAIL" Unit="DAYS" Value="0" />
    ...
</RevocationConstraints>
----
                                                            a|[source,xml]
----
<CertificateConstraints>
    ...
    <RevocationFreshness Level="FAIL" Unit="DAYS" Value="0" />
    ...
</CertificateConstraints>
----

|Revocation freshness +
(no time constraint)           a|[source,xml]
----
<CertificateConstraints>
    ...
    <RevocationDataFreshness Level="FAIL" />
    ...
</CertificateConstraints>

...

<RevocationConstraints>
    ...
	<!--<RevocationFreshness />-->
    ...
</RevocationConstraints>
----
                                                            a|[source,xml]
----
<CertificateConstraints>
    ...
    <RevocationFreshnessNextUpdate Level="FAIL" />
    ...
</CertificateConstraints>
----

|Signing-certificate reference certificate chain           a|[source,xml]
----
<CertificateConstraints>
    ...
    <SemanticsIdentifierForNaturalPerson />
    <SemanticsIdentifierForLegalPerson />
    ...
</CertificateConstraints>
----
                                                            a|[source,xml]
----
<CertificateConstraints>
    ...
    <SemanticsIdentifier>
        <Id>0.4.0.194121.1.1</Id> // for natural person
        <Id>0.4.0.194121.1.2</Id> // for legal person
    </SemanticsIdentifier>
    ...
</CertificateConstraints>
----

|===

[cols="2,5,5"]
.Policy changes from version 5.8 to 5.9
|===
|Title                      |v5.8                            |v5.9
|Revocation nextUpdate check           a|[source,xml]
----
<CertificateConstraints>
    ...
    <RevocationDataNextUpdatePresent />
    ...
</CertificateConstraints>
----
                                                            a|[source,xml]
----
<CertificateConstraints>
    ...
    <CRLNextUpdatePresent />
    <OCSPNextUpdatePresent />
    ...
</CertificateConstraints>
----

|Signing-certificate reference certificate chain           a|[source,xml]
----
<SignedAttributesConstraints>
    ...
    <AllCertDigestsMatch />
    ...
</SignedAttributesConstraints>
----
                                                            a|[source,xml]
----
<SignedAttributesConstraints>
    ...
    <SigningCertificateRefersCertificateChain />
    ...
</SignedAttributesConstraints>
----

|Qualified certificate check           a|[source,xml]
----
<SignedAttributesConstraints>
    ...
    <Qualification />
    ...
</SignedAttributesConstraints>
----
                                                            a|[source,xml]
----
<SignedAttributesConstraints>
    ...
    <PolicyQualificationIds /> <!-- pre eIDAS -->
    <QcCompliance /> <!-- post eIDAS -->
    ...
</SignedAttributesConstraints>
----

|QSCD/SSCD check           a|[source,xml]
----
<SignedAttributesConstraints>
    ...
    <SupportedByQSCD />
    ...
</SignedAttributesConstraints>
----
                                                            a|[source,xml]
----
<SignedAttributesConstraints>
    ...
    <QcSSCD />
    ...
</SignedAttributesConstraints>
----

|QcStatements attributes presence           a|[source,xml]
----
<SignedAttributesConstraints>
    ...
    <QCStatementIds />
    ...
</SignedAttributesConstraints>
----
                                                            a|[source,xml]
----
<SignedAttributesConstraints>
    ...
    <!-- Choose the corresponding QcStatement -->
    <QcCompliance />
    <MinQcEuLimitValue />
    <QcSSCD />
    <QcEuPDSLocation />
    <QcType />
    <QcLegislationCountryCodes />
    <SemanticsIdentifierForNaturalPerson />
    <SemanticsIdentifierForLegalPerson />
    <PSD2QcTypeRolesOfPSP />
    <!-- etc -->
    ...
</SignedAttributesConstraints>
----

|===