:sectnums:
:sectnumlevels: 5
:sourcetestdir: ../../../test/java
:samplesdir: ../_samples
:imagesdir: images/

== Privacy

=== Use of digested documents

Digested documents allow users to avoid sending the full document (detached signatures). Pre-computed digest values for a given document are used instead.

See section <<DSSDocuments>> for more information on digested documents.

=== Private information in logs

Five log levels are used in DSS:

* *ERROR* - is used for the most critical issues, interrupting a normal process workflow (encoding issues, not processable signed attributes, etc.).
* *WARN* - is used to indicate problems occurred during an executed process. Such issue does not stop or invalidate the process explicitly, but can have an impact on the final output.
* *INFO* - returns an important information to the logs.
* *DEBUG* - is used to print an extended information, such as token binaries, attribute values, etc.
* *TRACE* - is used to indicate the currently performing methods and state of objects.

When setting a log execution level to `ERROR`, `WARN` or `INFO` levels, no private information will be print to the log file. However, `DEBUG` and `TRACE` might potentially contain private information, as they display more information, including the source binaries of tokens.

Since the logs are hardcoded it is not possible to modify the behavior.
Therefore, to avoid disclosing private information, users should not use the DEBUG and TRACE levels. It is also not recommended using these two levels in the production.

For example, when an error occurs on a certificate reading, DSS only WARN users that an error occurred. However, if the log level is set to DEBUG on the user's side, the binaries of the failed certificate are printed.

Sometimes, DSS uses mixing rules for logging, such as it displays more information within a `WARN` or `INFO` level when `DEBUG` level is enabled.

=== Client-side signature creation with server-side remote key activation

With DSS it is possible to sign a document without needing to send it to the signing server. This is useful for users who do not want signing servers to have access to the information contained in their documents. Such a process is possible because DSS decomposes the signature of a document in three atomic steps.
See section <<SignatureCreationThreeSteps>> for an extensive description of these steps.

The first step is performed by the client and consists in the computation of the digest to be signed (hash of the document and of the signed attributes). The client sends the hash to the server. As a second step the server encrypts the hash using the private key and sends the signature value back to the client. The third step takes place at the client-side. The client adds the signature value to the appropriate field.

For code illustrations of the different steps, see the <<Topology>> section in the Annex.
