:sectnums:
:sectnumlevels: 5
:sourcetestdir: ../../../test/java
:samplesdir: ../_samples
:imagesdir: ../images/

[[RequestingTimestampToken]]
== Requesting a timestamp token in DSS
Timestamping is essential when creating digital signatures that need to be preserved. Refer to section <<Timestamps>> for information about the general principles of the timestamping process. The following sections present how a timestamp token can be requested in DSS.

=== Configuring timestamp sources

The DSS framework proposes a `TSPSource` interface to implement the communication with a Time Stamp Authority (see section <<TSA>> for more information on Time Stamp Authorities). The class `OnlineTSPSource` is the default implementation of `TSPSource` using a HTTP(S) communication layer.

The following snippet of Java code illustrates how you might use this class:

[source,java,indent=0]
.OnlineTSPSource use
----
include::{sourcetestdir}/eu/europa/esig/dss/cookbook/example/sources/OnlineTSPSourceTest.java[tags=demo]
----

==== Timestamp policy

A time-stamp policy is a "named set of rules that indicates the applicability of a time-stamp token to a particular community and/or class of application with common security requirements". A TSA may define its own policy which enhances the policy defined in https://datatracker.ietf.org/doc/html/rfc3628[RFC 3628]. Such a policy shall incorporate or further constrain the requirements identified in RFC 3628. The user may request the TSA to issue a timestamp under a specific time-stamp policy that is supported by the TSA.

[source,java,indent=0]
.Timestamp policy
----
include::{sourcetestdir}/eu/europa/esig/dss/cookbook/example/sources/OnlineTSPSourceTest.java[tags=policy]
----

==== Composite TSP sources

Sometimes timestamping servers may encounter interruptions (e.g. restart, configuration issues, etc.). To avoid failing signature augmentation, DSS allows a user to configure several TSP Sources. DSS will try one source after the other until getting a usable timestamp token.

[source,java,indent=0]
.Configuration of a CompositeTSPSource
----
include::{sourcetestdir}/eu/europa/esig/dss/cookbook/example/sources/CompositeTSPSourceTest.java[tags=demo]
----

[[KeyStoreTSPSource]]
==== KeyStore TSP source

Starting from version `5.13` DSS provides a `KeyStoreTSPSource` implementation allowing to create timestamps using a local key store. The implementation is provided mainly for test purposes and creation of local timestamps.

[source,java,indent=0]
.Configuration of a KeyStoreTSPSource
----
include::{sourcetestdir}/eu/europa/esig/dss/cookbook/example/sources/KeyStoreTSPSourceTest.java[tags=demo]
----