:sectnums:
:sectnumlevels: 5
:sourcetestdir: ../../../test/java
:samplesdir: ../_samples
:imagesdir: images/

[[RetrievingRevocationData]]
== Retrieving revocation data in DSS

A CRL is a time-stamped list identifying revoked certificates. It is signed by a Certificate Authority (CA) and made freely available in a public repository. Each revoked certificate is identified in a CRL by its certificate serial number.

The Online Certificate Status Protocol (OCSP) is an Internet protocol used for obtaining the revocation status of a unique X.509 digital certificate.

For every certificate, the validity has to be checked via CRL or OCSP responses. The information may originate from different CRLSources or OCSPSources:
For easing the usage of such sources, DSS implements a CRLSource and OCSPSource interfaces (which inherit from RevocationSource), which offer a generic, uniform way of accessing CRL and OCSP sources. Furthermore, a caching mechanism can be easily attached to those sources, optimizing the access time to revocation information by reducing network connections to online servers.

The interface CRLSource defines the method which returns CRLToken for the given certificate/issuer certificate couple:

[source,java,indent=0]
.CRLSource usage
----
include::{sourcetestdir}/eu/europa/esig/dss/cookbook/example/snippets/CRLSourceSnippet.java[tags=demo]
----

The interface OCSPSource defines the method which returns OCSPToken for the given certificate/issuer certificate couple:

[source,java,indent=0]
.OCSPSource usage
----
include::{sourcetestdir}/eu/europa/esig/dss/cookbook/example/snippets/OCSPSourceSnippet.java[tags=demo]
----

We use these classes during the certificate validation process through "validationContext" object (based on ValidationContext class) which is a "cache" for one validation request that contains every object retrieved so far. This object in turn instantiates a "verifier" based on `RevocationDataLoadingStrategy` class whose role is to fetch revocation data by querying an OCSP or CRL source in the defined order and return the succeeded result.
In general, we can distinguish three main sources:

* Offline sources (`OfflineRevocationSource`);
* Online sources (`OnlineRevocationSource`);
* Sources with the cache mechanism;
* List of sources (`ListRevocationSource`) with a collection of several sources.


=== Caching

The above-mentioned class allows caching of CRL and OCSP responses to a user-chosen source. By default DSS provides a JDBC based implementation for this class, but other implementations also can be created. The class contains a complete set of functions to save revocation data to a database, extract, update and remove it. +
Furthermore, the `RepositoryRevocationSource` allows the implementer to define a backup revocation source, for the case if the database does not contain the certificate's revocation data yet. +

List of cached Revocation sources implemented in DSS:

* `JdbcRevocationSource`
** `JdbcCacheCRLSource`
** `JdbcCacheOCSPSource`

Be aware that you have to initialize a table before you start working with the cached revocation repository.

==== CRL
An example for JdbcCacheCRLSource :

[source,java,indent=0]
.JdbcCacheCRLSource usage
----
include::{sourcetestdir}/eu/europa/esig/dss/cookbook/example/snippets/CRLSourceSnippet.java[tags=demo-cached]
----

==== OCSP
An example for JdbcCacheOCSPSource :

[source,java,indent=0]
.JdbcCacheOCSPSource usage
----
include::{sourcetestdir}/eu/europa/esig/dss/cookbook/example/snippets/OCSPSourceSnippet.java[tags=demo-cached]
----


=== Online fetching
WARNING: By default, revocation data are not fetched from untrusted sources.


==== CRL

This is a representation of an Online CRL repository. This implementation will contact using HTTP protocol the CRL Responder to download the CRLs from the given URI. Note that the certificate's Authority Information Access (AIA) extension is used to find issuer's resources location like CRL file and/or Online Certificate Status Protocol (OCSP). The URIs of CRL server will be extracted from this property (OID value: 1.3.6.1.5.5.7.48.1.3).

It allows the following configuration :

[source,java,indent=0]
.OnlineCRLSource usage
----
include::{sourcetestdir}/eu/europa/esig/dss/cookbook/example/snippets/CRLSourceSnippet.java[tags=demo-online]
----

==== OCSP
This is a representation of an Online OCSP repository. This implementation will contact using HTTP protocol the OCSP Responder to retrieve the OCSP response. Note that the certificate's Authority Information Access (AIA) extension is used to find issuer's resources location like CRT file and/or Online Certificate Status Protocol (OCSP). The URIs of OCSP server will be extracted from this property (OID value: 1.3.6.1.5.5.7.48.1).

It allows the following configuration :

[source,java,indent=0]
.OnlineOCSPSource usage
----
include::{sourcetestdir}/eu/europa/esig/dss/cookbook/example/snippets/OCSPSourceSnippet.java[tags=demo-online]
----


=== Other implementations of CRL and OCSP Sources
Such sources find the status of a certificate either from a list stored locally or using the information contained in the advanced signature or online way. Here is the list of sources already implemented in the DSS framework:

* CRL sources
** `OfflineCRLSource` : This class implements the `OfflineRevocationSource` and retrieves the revocation data from extracted information. The code is common for all signature formats and CRL contents are injected by its sub-classes :
*** `CMSCRLSource` : Extracts CRLs and CRL references from a CMS Signed Data :
**** `CAdESCRLSource` : Sub-class of `CMSCRLSource` for a CAdES Signature;
**** `TimestampCRLSource`: Sub-class of `CMSCRLSource` for a Timestamp token (RFC 3161);
*** `PAdESCRLSource` : Extracts CRLs and CRL references from a PAdES signature.
*** `XAdESCRLSource` : Extracts CRLs and CRL references from a XAdES signature.
*** `ExternalResourcesCRLSource` : A class that can instantiate a list of certificate revocation lists from a directory where the individual lists should be.
** `OnlineCRLSource` : Retrieves CRL files from online sources with the CRL Distribution Points information from the certificate.
** `JdbcCacheCrlSource` : Implementation of the `JdbcRevocationSource`. This implementation allows storage of valid CRL entries to a defined `DataSource'` and retrieve them locally.

* OCSP sources
** `OfflineOCSPSource` : This class implements the `OfflineRevocationSource` and retrieves the revocation data from extracted information. The code is common for all signature formats and OCSP responses are injected by its sub-classes :
*** `CMSOCSPSource` : Extracts OCSP responses and OCSP references from a CMS Signed Data :
**** `CAdESOCSPSource` : Sub-class of `CMSOCSPSource` for a CAdES Signature;
**** `TimestampOCSPSource`: Sub-class of `CMSOCSPSource` for a Timestamp token (RFC 3161);
*** `PAdESOCSPSource` : Extracts OCSP responses and OCSP references from a PAdES signature.
*** `XAdESOCSPSource` : Extracts OCSP responses and OCSP references from a XAdES signature.
**** `ExternalResourcesOCSPSource` : A class that can instantiate a list of OCSPToken from a directory where should be the individual DER Encoded X509 certificates files.
** `OnlineOCSPSource` : Retrieves OCSP responses from online source.
** `JdbcCacheOcspSource` : Implementation of the `JdbcRevocationSource`. This implementation allows storage of valid OCSP entries to a defined `DataSource` and retrieve them locally.



=== Check OCSP or CRL first
Since version 5.9+, DSS allows the use of a RevocationDataLoadingStrategy. The latter defines logic for loading OCSP or CRL data. Two strategies are available:

* OCSPFirstRevocationDataLoadingStrategy: loads OCSP first, if not available or the response is invalid, then tries to load CRL and returns the first succeeded result. This strategy is used by default for revocation retrieving.
* CRLFirstRevocationDataLoadingStrategy: fetches firstly CRL response, if not available, tries OCSP and returns the first succeeded result.

See section <<certificateVerifier>> for an example of how to use a RevocationDataLoadingStrategy.

Using an OCSP first has some advantages. A first one is that there is a potential gain of freshness compared to using CRLs. In case the OSCP sends queries to a database that is updated in real time or every x hours, the information fetched by the OCSP is more recent (thisUpdate field) than the information contained in the CRL, given that the CRL is built from that database. In the worst case the OCSP uses the data contained in the CRL and they both have the same thisUpdate field. The information fetched by an OCSP will never be older than the one obtained from a CRL.

A second advantage is that the certificate that signed the OCSP response might contain an OCSPNoCheck extension. This extension indicates that the revocation data of the certificate that contains the public key linked to the private key that was used to sign the OCSP response does not need to be checked.

WARNING: When the OCSPNoCheck extension is used and the OCSP responder's key is comprised, it is as if the key used by the CA to sign the CRL was compromised. The whole hierarchy falls down. To lower the risk, the CA might decide to issue certificates of OCSP responders with a very short lifetime and decide to renew them frequently.

A third advantage of OCSPs is that getting the response takes less time than with CRLs. CRLs can take a long time to be downloaded. There is also no obligation to sort CRLs according to serial number which means that the whole list needs to be browsed until finding the searched serial number.